Repository flux3dp/beam-studio-core, pull requests merged in 2021-06, with the labels that each got.

#68 rewrite requireNode with import
  package.json
  src/web/app/views/beambox/Color-Picker-Panel.tsx
  src/web/app/views/beambox/Photo-Edit-Panel.tsx
  src/web/app/views/beambox/Right-Panels/Layer-Panel.tsx
  src/web/app/views/beambox/Right-Panels/Options-Blocks/Text-Options.tsx
  src/web/app/views/beambox/Tool-Panels/RowColumn.tsx
  src/web/app/views/beambox/Zoom-Block/Zoom-Block.tsx
  src/web/app/widgets/Dropdown-Control.tsx
  src/web/helpers/api/control.ts
  src/web/helpers/api/svg-laser-parser.ts
  src/web/helpers/auto-save-helper.ts
  src/web/helpers/output-error.ts
  src/web/helpers/pdf-helper.ts
  src/web/helpers/rsa-key.ts
  src/web/helpers/symbol-maker.ts
  src/web/interfaces/IFileSystem.d.ts
  src/web/interfaces/IStorage.d.ts
  yarn.lock
Labels: size/L

#69 Fix requirenode os
  src/implementations/os.ts
  src/web/app/views/beambox/Network-Testing-Panel.tsx
  src/web/app/views/beambox/Photo-Edit-Panel.tsx
  src/web/helpers/output-error.ts
  src/web/helpers/smart-upnp.ts
  src/web/interfaces/IOperatingSystem.d.ts
Labels: size/L

#70 handle electron lib
  src/implementations/communicator.ts
  src/implementations/cookies.ts
  src/implementations/menu.ts
  src/web/app/actions/beambox/beambox-init.ts
  src/web/app/pages/Home.tsx
  src/web/app/svgedit/svgcanvas.ts
  src/web/app/views/FluxIdLogin.tsx
  src/web/helpers/api/flux-id.ts
  src/web/helpers/auto-save-helper.ts
  src/web/helpers/menubar.ts
  src/web/helpers/pdf-helper.ts
  src/web/helpers/shadow-window.ts
  src/web/interfaces/ICommunicator.d.ts
  src/web/interfaces/ICookies.d.ts
  src/web/interfaces/IFileSystem.d.ts
  src/web/interfaces/IMenu.d.ts
Labels: size/L

#71 clean the rest require node
  src/implementations/network.ts
  src/web/app/pages/Connect-Machine-Ip.tsx
  src/web/app/views/beambox/Network-Testing-Panel.tsx
  src/web/app/views/beambox/Task-Interpreter-Panel.tsx
  src/web/app/views/beambox/Zoom-Block/Zoom-Block.tsx
  src/web/helpers/api/discover.ts
  src/web/helpers/menubar.ts
  src/web/helpers/pdf-helper.ts
  src/web/interfaces/IMenu.d.ts
  src/web/interfaces/INetwork.d.ts
  src/web/interfaces/IOperatingSystem.d.ts
Labels: size/L

#72 Update diode laser
  src/web/app/actions/beambox/diode-boundary-drawer.ts
  src/web/app/lang/de.ts
  src/web/app/lang/en.ts
  src/web/app/lang/es.ts
  src/web/app/lang/ja.ts
  src/web/app/lang/zh-cn.ts
  src/web/app/lang/zh-tw.ts
  src/web/app/views/beambox/Right-Panels/Laser-Panel.tsx
  src/web/helpers/api/alert-config.ts
Labels: size/XXL

#73 add ButtonGroup test
  src/web/app/views/Update-Dialog.tsx
  src/web/app/views/__snapshots__/Update-Dialog.spec.tsx.snap
  src/web/app/views/beambox/DxfDpiSelector.tsx
  src/web/app/views/beambox/Photo-Edit-Panel.tsx
  src/web/app/views/dialogs/Confirm-Prompt.tsx
  src/web/app/views/dialogs/Prompt.tsx
  src/web/app/widgets/Alert.tsx
  src/web/app/widgets/AlertDialog.tsx
  src/web/app/widgets/Button-Group.tsx
  src/web/app/widgets/ButtonGroup.spec.tsx
  src/web/app/widgets/ButtonGroup.tsx
  src/web/app/widgets/Progress.tsx
  src/web/app/widgets/__snapshots__/ButtonGroup.spec.tsx.snap
Labels: size/L

#75 remove ipc and events dependencies
  src/web/app/actions/beambox/export-funcs.ts
  src/web/app/actions/beambox/font-funcs.ts
  src/web/app/actions/global-interaction.ts
  src/web/app/actions/global.ts
  src/web/app/pages/Beambox.tsx
  src/web/helpers/electron-updater.ts
  src/web/helpers/file-export-helper.ts
  src/web/helpers/symbol-maker.ts
  src/web/interfaces/ICommunicator.d.ts
Labels: size/L

#77 add tests
  src/web/app/actions/dialog-caller.tsx
  src/web/app/pages/FluxIdLogin.spec.tsx
  src/web/app/pages/FluxIdLogin.tsx
  src/web/app/pages/__snapshots__/FluxIdLogin.spec.tsx.snap
  src/web/app/views/beambox/About-Beam-Studio.tsx
  src/web/app/views/beambox/AboutBeamStudio.spec.tsx
  src/web/app/views/beambox/AboutBeamStudio.tsx
  src/web/app/views/beambox/RatingPanel.spec.tsx
  src/web/app/views/beambox/RatingPanel.tsx
  src/web/app/views/beambox/__snapshots__/AboutBeamStudio.spec.tsx.snap
  src/web/app/views/beambox/__snapshots__/RatingPanel.spec.tsx.snap
  src/web/setupTests.ts
Labels: size/XXL

#78 extract ChangeLog interface
  src/implementations/changelog.ts
  src/web/app/actions/dialog-caller.tsx
  src/web/app/views/dialogs/Change-Log.tsx
  src/web/app/views/dialogs/ChangeLogDialog.spec.tsx
  src/web/app/views/dialogs/ChangeLogDialog.tsx
  src/web/app/views/dialogs/__snapshots__/ChangeLogDialog.spec.tsx.snap
  src/web/interfaces/IChangeLog.d.ts
  src/web/setupTests.ts
Labels: size/XL

#79 retrieve object from window; otherwise it will disappear due to unknown reasons in web
  public/js/lib/svgeditor/coords.js
  public/js/lib/svgeditor/recalculate.js
Labels: size/XS

#81 Fix rotate un/redo related bugs
  src/web/app/svgedit/svgcanvas.ts
Labels: size/XS

#74 use eventemitter3 which is compatible for both node and browser
  package.json
  src/web/app/stores/alert-store.ts
  src/web/app/stores/beambox-store.ts
  src/web/app/views/beambox/Noun-Project-Panel.tsx
  src/web/helpers/api/beam-easy-api.ts
  src/web/helpers/api/control.ts
  src/web/helpers/api/flux-id.ts
  src/web/helpers/api/open-cv.ts
  yarn.lock
Labels: size/M

#83 Seperate text related function from svgcanvas
  src/web/app/actions/beambox/font-funcs.ts
  src/web/app/actions/beambox/svg-editor.ts
  src/web/app/svgedit/history.ts
  src/web/app/svgedit/svgcanvas.ts
  src/web/app/svgedit/textactions.ts
  src/web/app/svgedit/textedit.ts
  src/web/app/views/beambox/Right-Panels/Actions-Panel.tsx
  src/web/app/views/beambox/Right-Panels/Options-Blocks/Text-Options.tsx
  src/web/interfaces/IHistory.d.ts
Labels: size/XXL

#86 Remove notification
  src/web/app/actions/dialog-caller.tsx
  src/web/app/router.tsx
  src/web/app/stores/alert-store.ts
  src/web/app/views/Notification-Collection.tsx
  src/web/app/views/UpdateDialog.spec.tsx
  src/web/app/views/UpdateDialog.tsx
  src/web/app/views/__snapshots__/UpdateDialog.spec.tsx.snap
  src/web/helpers/firmware-updater.ts
Labels: size/L

#84 rewrite AlertProgressContext
  src/web/app/actions/alert-caller.spec.tsx
  src/web/app/actions/alert-caller.tsx
  src/web/app/actions/progress-caller.spec.ts
  src/web/app/actions/progress-caller.ts
  src/web/app/constants/progress-constants.ts
  src/web/app/contexts/AlertProgressContext.tsx
  src/web/app/router.tsx
  src/web/app/views/dialogs/AlertAndProgress.tsx
  src/web/app/views/tutorials/Tutorial.tsx
  src/web/app/views/tutorials/TutorialContext.tsx
  src/web/app/widgets/Input-Lightbox.tsx
  src/web/app/widgets/Progress.spec.tsx
  src/web/app/widgets/Progress.tsx
  src/web/app/widgets/Select.spec.tsx
  src/web/app/widgets/Select.tsx
  src/web/app/widgets/__snapshots__/Progress.spec.tsx.snap
  src/web/helpers/eventEmitterFactory.ts
  src/web/interfaces/IProgress.d.ts
Labels: size/XL

#87 Add type FontDescriptorKeys
  src/web/interfaces/IFont.d.ts
Labels: size/S

#85 rewrite tutorial context
  src/web/app/actions/beambox/svg-editor.ts
  src/web/app/actions/beambox/svgeditor-function-wrapper.ts
  src/web/app/actions/dialog-caller.tsx
  src/web/app/svgedit/svgcanvas.ts
  src/web/app/views/beambox/Right-Panels/Laser-Panel.tsx
  src/web/app/views/beambox/Right-Panels/Layer-Panel.tsx
  src/web/app/views/beambox/Right-Panels/Right-Panel.tsx
  src/web/app/views/beambox/Top-Bar/Top-Bar.tsx
  src/web/app/views/tutorials/Tutorial-Controller.tsx
  src/web/app/views/tutorials/Tutorial.tsx
  src/web/app/views/tutorials/TutorialContext.tsx
  src/web/app/views/tutorials/tutorialController.spec.ts
  src/web/app/views/tutorials/tutorialController.ts
  src/web/app/widgets/Dialog-Box.spec.tsx
  src/web/app/widgets/Dialog-Box.tsx
  src/web/app/widgets/__snapshots__/Dialog-Box.spec.tsx.snap
Labels: size/L

#88 rewrite DialogContext
  src/web/app/actions/dialog-caller.tsx
  src/web/app/contexts/DialogContext.tsx
  src/web/app/router.tsx
  src/web/app/views/dialogs/Dialog.tsx
Labels: size/L

#89 add tests
  src/web/app/actions/beambox/Tool-Panels-Controller.tsx
  src/web/app/actions/beambox/imageTracePanelController.spec.tsx
  src/web/app/actions/beambox/imageTracePanelController.tsx
  src/web/app/actions/beambox/svg-editor.ts
  src/web/app/actions/beambox/svgeditor-function-wrapper.ts
  src/web/app/actions/beambox/toolPanelsController.spec.tsx
  src/web/app/actions/beambox/toolPanelsController.tsx
  src/web/app/constants/connection-constants.ts
  src/web/app/constants/error-constants.ts
  src/web/app/constants/input-lightbox-constants.ts
  src/web/app/stores/beambox-store.spec.ts
  src/web/app/stores/beambox-store.ts
  src/web/app/svgedit/svgcanvas.ts
  src/web/app/views/beambox/Document-Panels/Document-Panel.tsx
  src/web/app/views/beambox/Tool-Panels/Tool-Panels.tsx
  src/web/app/widgets/EngraveDpiSlider.spec.tsx
  src/web/app/widgets/EngraveDpiSlider.tsx
  src/web/app/widgets/__snapshots__/EngraveDpiSlider.spec.tsx.snap
Labels: size/XL

#90 IDE doesn't rename all references
  src/web/app/views/beambox/Left-Panels/Left-Panel.tsx
Labels: size/XS

#91 exclude files/folders from coverage report
  .github/workflows/beam-studio-core-ci.yml
  README.md
  jest.config.js
Labels: size/S

#92 Remove unused element in svg-editor.tsx
  public/js/lib/svgeditor/extensions/ext-connector.js
  public/js/lib/svgeditor/extensions/ext-foreignobject.js
  public/js/lib/svgeditor/extensions/ext-polygon.js
  public/js/lib/svgeditor/extensions/ext-star.js
  src/web/app/actions/beambox/svg-editor.ts
  src/web/app/pages/__snapshots__/svg-editor.spec.tsx.snap
  src/web/app/pages/svg-editor.tsx
  src/web/app/svgedit/textactions.ts
Labels: size/XXL

#93 Move clipboard functions and delete out
  src/web/app/actions/beambox/beambox-global-interaction.ts
  src/web/app/actions/beambox/svg-editor.ts
  src/web/app/svgedit/operations/clipboard.ts
  src/web/app/svgedit/operations/delete.ts
  src/web/app/svgedit/svgcanvas.ts
  src/web/app/svgedit/textactions.ts
  src/web/app/widgets/Curve-Control.tsx
Labels: size/XL

#95 make Dialog support styled component
  src/web/app/views/dialogs/Dialog.tsx
Labels: size/S

#97 Fix dialog props
  src/web/app/router.tsx
Labels: size/L

#96 rewrite zoom block context
  src/web/app/contexts/DialogContext.spec.tsx
  src/web/app/contexts/__snapshots__/DialogContext.spec.tsx.snap
  src/web/app/pages/Beambox.tsx
  src/web/app/svgedit/svgcanvas.ts
  src/web/app/views/beambox/Zoom-Block/contexts/Zoom-Block-Context.tsx
  src/web/app/views/beambox/Zoom-Block/contexts/Zoom-Block-Controller.tsx
  src/web/app/views/beambox/ZoomBlock/ZoomBlock.tsx
  src/web/app/views/beambox/ZoomBlock/contexts/ZoomBlockContext.spec.tsx
  src/web/app/views/beambox/ZoomBlock/contexts/ZoomBlockContext.tsx
  src/web/app/views/beambox/ZoomBlock/contexts/ZoomBlockController.spec.tsx
  src/web/app/views/beambox/ZoomBlock/contexts/ZoomBlockController.tsx
Labels: size/L

#99 Fix global interactions
  src/web/app/actions/global-interaction.ts
Labels: size/S

#100 Update dialog interface for web version
  src/web/app/actions/beambox/beambox-init.ts
  src/web/app/actions/beambox/export-funcs.ts
  src/web/app/contexts/Monitor-Context.tsx
  src/web/app/views/beambox/Right-Panels/Actions-Panel.tsx
  src/web/app/views/beambox/Right-Panels/Laser-Panel.tsx
  src/web/helpers/file-export-helper.ts
  src/web/helpers/output-error.ts
  src/web/interfaces/IDialog.d.ts
Labels: size/L

#98 make Alert support styled component
  src/web/app/views/dialogs/AlertAndProgress.tsx
Labels: size/XS

#101 Fix web workarea size bug
  src/web/app/actions/beambox/svg-editor.ts
Labels: size/XS

#102 rewrite top bar context
  src/web/app/actions/beambox/svg-editor.ts
  src/web/app/pages/Beambox.tsx
  src/web/app/svgedit/svgcanvas.ts
  src/web/app/views/beambox/Top-Bar/Top-Bar-Hints.tsx
  src/web/app/views/beambox/Top-Bar/contexts/Top-Bar-Controller.tsx
  src/web/app/views/beambox/Top-Bar/contexts/Top-Bar-Hints-Controller.ts
  src/web/app/views/beambox/TopBar/TopBar.tsx
  src/web/app/views/beambox/TopBar/TopBarHints.spec.tsx
  src/web/app/views/beambox/TopBar/TopBarHints.tsx
  src/web/app/views/beambox/TopBar/__snapshots__/TopBarHints.spec.tsx.snap
  src/web/app/views/beambox/TopBar/contexts/TopBarContext.spec.tsx
  src/web/app/views/beambox/TopBar/contexts/TopBarContext.tsx
  src/web/app/views/beambox/TopBar/contexts/TopBarController.spec.tsx
  src/web/app/views/beambox/TopBar/contexts/TopBarController.tsx
  src/web/app/views/beambox/TopBar/contexts/TopBarHintsContext.spec.tsx
  src/web/app/views/beambox/TopBar/contexts/TopBarHintsContext.tsx
  src/web/app/views/beambox/TopBar/contexts/TopBarHintsController.spec.ts
  src/web/app/views/beambox/TopBar/contexts/TopBarHintsController.ts
  src/web/helpers/api/flux-id.ts
  src/web/helpers/eventEmitterFactory.ts
Labels: size/XL

#103 rewrite TimeEstimationButton
  src/web/app/pages/Beambox.tsx
  src/web/app/svgedit/svgcanvas.ts
  src/web/app/views/beambox/Right-Panels/Laser-Panel.tsx
  src/web/app/views/beambox/Time-Estimation-Button/Time-Estimation-Button-Controller.ts
  src/web/app/views/beambox/Time-Estimation-Button/Time-Estimation-Button.tsx
  src/web/app/views/beambox/TimeEstimationButton/TimeEstimationButton.spec.tsx
  src/web/app/views/beambox/TimeEstimationButton/TimeEstimationButton.tsx
  src/web/app/views/beambox/TimeEstimationButton/TimeEstimationButtonContext.spec.tsx
  src/web/app/views/beambox/TimeEstimationButton/TimeEstimationButtonContext.tsx
  src/web/app/views/beambox/TimeEstimationButton/TimeEstimationButtonController.spec.ts
  src/web/app/views/beambox/TimeEstimationButton/TimeEstimationButtonController.ts
  src/web/app/views/beambox/TimeEstimationButton/__snapshots__/TimeEstimationButton.spec.tsx.snap
  src/web/helpers/api/flux-id.ts
  src/web/helpers/eventEmitterFactory.ts
Labels: size/L

#104 split Left Panel
  src/web/app/pages/Skip-Connect-Machine.tsx
  src/web/app/pages/svg-editor.spec.tsx
  src/web/app/views/beambox/Left-Panels/Left-Panel.tsx
  src/web/app/views/beambox/LeftPanel/DrawingToolButtonGroup.spec.tsx
  src/web/app/views/beambox/LeftPanel/DrawingToolButtonGroup.tsx
  src/web/app/views/beambox/LeftPanel/LeftPanel.spec.tsx
  src/web/app/views/beambox/LeftPanel/LeftPanel.tsx
  src/web/app/views/beambox/LeftPanel/PreviewToolButtonGroup.tsx
  src/web/app/views/beambox/LeftPanel/__snapshots__/DrawingToolButtonGroup.spec.tsx.snap
  src/web/app/views/beambox/LeftPanel/__snapshots__/LeftPanel.spec.tsx.snap
  src/web/app/views/beambox/TopBar/TopBar.tsx
  src/web/main.ts
  src/web/setupTests.ts
Labels: size/XXL

#108 Update camera transmit fail judging
  src/web/helpers/api/camera.ts
Labels: size/L

#109 Fix DIODE_CALIBRATION binary having wrong offset
  src/web/app/constants/device-constants.ts
Labels: size/XS

#106 Add tests 2
  src/web/app/views/FluxIdLogin.tsx
  src/web/app/widgets/InputLightbox.spec.tsx
  src/web/app/widgets/Modal-With-Hole.spec.tsx
  src/web/app/widgets/PathInput.spec.tsx
  src/web/app/widgets/PathInput.tsx
  src/web/app/widgets/ShowablePasswordInput.spec.tsx
  src/web/app/widgets/ShowablePasswordInput.tsx
  src/web/app/widgets/__snapshots__/PathInput.spec.tsx.snap
  src/web/app/widgets/__snapshots__/ShowablePasswordInput.spec.tsx.snap
  src/web/helpers/is-json.spec.ts
  src/web/helpers/is-json.ts
  src/web/helpers/is-object-empty.spec.ts
  src/web/helpers/is-object-empty.ts
  src/web/helpers/monitor-status.spec.ts
  src/web/helpers/rsa-key.spec.ts
Labels: size/L

#107 rewrite some monitor views
  src/web/app/contexts/Monitor-Context.tsx
  src/web/app/views/monitor/Monitor-Control.tsx
  src/web/app/views/monitor/Monitor.tsx
  src/web/app/views/monitor/MonitorControl.spec.tsx
  src/web/app/views/monitor/MonitorControl.tsx
  src/web/app/views/monitor/MonitorHeader.spec.tsx
  src/web/app/views/monitor/MonitorHeader.tsx
  src/web/app/views/monitor/MonitorTask.spec.tsx
  src/web/app/views/monitor/MonitorTask.tsx
  src/web/app/views/monitor/__snapshots__/MonitorControl.spec.tsx.snap
  src/web/app/views/monitor/__snapshots__/MonitorHeader.spec.tsx.snap
  src/web/app/views/monitor/__snapshots__/MonitorTask.spec.tsx.snap
Labels: size/XXL

#110 Update diode default
  src/web/app/actions/beambox/beambox-preference.spec.ts
  src/web/app/actions/beambox/beambox-preference.ts
  src/web/app/actions/beambox/constant.ts
  src/web/app/constants/right-panel-constants.ts
  src/web/app/views/beambox/Diode-Calibration.tsx
  src/web/helpers/device-master.ts
Labels: size/L

#111 Fix disassemble wireframe bugs
  public/js/lib/svgeditor/recalculate.js
  src/web/app/svgedit/svgcanvas.ts
Labels: size/S

#112 Update diode preview safe distance to match limit
  src/web/app/actions/beambox/constant.ts
Labels: size/XS

#113 Use webpack worker loader to load worker
  src/web/helpers/symbol-helper/image-symbol-worker.ts
  src/web/helpers/symbol-helper/image-symbol.worker.ts
  src/web/helpers/symbol-maker.ts
Labels: size/M

#114 refactor menu click
  src/implementations/menuEventListenerFactory.ts
  src/web/app/actions/beambox/beambox-global-interaction.ts
  src/web/app/actions/beambox/beambox-init.ts
  src/web/app/actions/beambox/menuActions.ts
  src/web/app/actions/beambox/menuDeviceActions.ts
  src/web/app/actions/global-interaction.ts
  src/web/interfaces/IMenuEventListenerFactory.ts
Labels: size/XL

#117 Remove shadow-window.ts
  src/web/helpers/shadow-window.ts
Labels: size/M

#116 abstract menu and move out electron code
  package.json
  src/implementations/customMenuActionProvider.ts
  src/implementations/menu.ts
  src/implementations/recentMenuUpdater.ts
  src/web/app/actions/beambox/beambox-init.ts
  src/web/app/actions/beambox/menuActions.ts
  src/web/app/actions/beambox/svg-editor.ts
  src/web/app/pages/Home.tsx
  src/web/app/router.tsx
  src/web/app/svgedit/svgcanvas.ts
  src/web/helpers/menubar.ts
  src/web/helpers/menubar/AbstractMenu.ts
  src/web/helpers/menubar/electron-menubar-helper.ts
  src/web/helpers/menubar/view.ts
  src/web/interfaces/ICustomMenuActionProvider.d.ts
  src/web/interfaces/IMenu.d.ts
  src/web/interfaces/IRecentMenuUpdater.d.ts
  src/web/loader.ts
  src/web/main.ts
  src/web/setupTests.ts
  yarn.lock
Labels: size/XL

#118 Fix import js
  src/web/app/actions/beambox/svg-editor.ts
Labels: size/S

#119 Fix ObjectPanelController getDimensionValues
  src/web/app/views/beambox/Right-Panels/contexts/ObjectPanelController.spec.tsx
  src/web/app/views/beambox/Right-Panels/contexts/ObjectPanelController.tsx
Labels: size/XS

#120 merge top bar menu code
  package.json
  src/web/app/lang/de.ts
  src/web/app/lang/en.ts
  src/web/app/lang/es.ts
  src/web/app/lang/ja.ts
  src/web/app/lang/zh-cn.ts
  src/web/app/lang/zh-tw.ts
  src/web/app/views/beambox/TopBar/Menu/Menu.tsx
  src/web/helpers/eventEmitterFactory.ts
  src/web/interfaces/ILang.d.ts
  yarn.lock
Labels: size/XXL

#122 move icon into img folder for web compatibility
  src/web/app/views/beambox/AboutBeamStudio.tsx
  src/web/app/views/beambox/RatingPanel.tsx
  src/web/app/views/beambox/TopBar/Menu.tsx
  src/web/app/views/beambox/__snapshots__/AboutBeamStudio.spec.tsx.snap
  src/web/app/views/beambox/__snapshots__/RatingPanel.spec.tsx.snap
  src/web/app/views/dialogs/ChangeLogDialog.tsx
  src/web/app/views/dialogs/__snapshots__/ChangeLogDialog.spec.tsx.snap
Labels: size/M

#123 add tests
  src/web/app/lang/de.ts
  src/web/app/lang/en.ts
  src/web/app/lang/es.ts
  src/web/app/lang/ja.ts
  src/web/app/lang/zh-cn.ts
  src/web/app/lang/zh-tw.ts
  src/web/app/views/beambox/Color-Picker-Panel.tsx
  src/web/app/views/beambox/ColorPickerPanel.spec.tsx
  src/web/app/views/beambox/ColorPickerPanel.tsx
  src/web/app/views/beambox/Right-Panels/LayerPanel.tsx
  src/web/app/views/beambox/TopBar/Menu.spec.tsx
  src/web/app/views/beambox/TopBar/Menu.tsx
  src/web/app/views/beambox/TopBar/__snapshots__/Menu.spec.tsx.snap
  src/web/app/views/beambox/__snapshots__/ColorPickerPanel.spec.tsx.snap
  src/web/interfaces/ILang.d.ts
  src/web/setupTests.ts
Labels: size/XXL

#124 1. import a new blob lib which is compatible for both web and Node 2. implement importing examples 3. fix tests
  package.json
  src/web/app/actions/beambox/menuActions.ts
  src/web/app/views/beambox/TopBar/Menu.spec.tsx
  src/web/app/views/beambox/TopBar/Menu.tsx
  src/web/app/views/beambox/TopBar/__snapshots__/Menu.spec.tsx.snap
  yarn.lock
Labels: size/L

#125 use react router
  package.json
  src/web/app/actions/global.ts
  src/web/app/pages/Beambox.tsx
  src/web/app/pages/ConnectEthernet.spec.tsx
  src/web/app/pages/ConnectEthernet.tsx
  src/web/app/pages/ConnectMachineIp.tsx
  src/web/app/pages/ConnectWiFi.spec.tsx
  src/web/app/pages/ConnectWiFi.tsx
  src/web/app/pages/ConnectWired.spec.tsx
  src/web/app/pages/ConnectWired.tsx
  src/web/app/pages/FluxIdLogin.spec.tsx
  src/web/app/pages/FluxIdLogin.tsx
  src/web/app/pages/Home.tsx
  src/web/app/pages/HomeView.spec.tsx
  src/web/app/pages/HomeView.tsx
  src/web/app/pages/SelectConnectionType.spec.tsx
  src/web/app/pages/SelectConnectionType.tsx
  src/web/app/pages/Settings.tsx
  src/web/app/pages/Skip-Connect-Machine.tsx
  src/web/app/pages/SkipConnectMachine.spec.tsx
  src/web/app/pages/SkipConnectMachine.tsx
  src/web/app/pages/__snapshots__/ConnectEthernet.spec.tsx.snap
  src/web/app/pages/__snapshots__/ConnectWiFi.spec.tsx.snap
  src/web/app/pages/__snapshots__/ConnectWired.spec.tsx.snap
  src/web/app/pages/__snapshots__/HomeView.spec.tsx.snap
  src/web/app/pages/__snapshots__/SelectConnectionType.spec.tsx.snap
  src/web/app/pages/__snapshots__/SkipConnectMachine.spec.tsx.snap
  src/web/app/pages/__snapshots__/svg-editor.spec.tsx.snap
  src/web/app/pages/svg-editor.spec.tsx
  src/web/app/router.tsx
  src/web/app/views/settings/Setting-General.tsx
  yarn.lock
Labels: size/L

#126 add preferences menu
  src/web/app/router.tsx
  src/web/app/views/beambox/TopBar/Menu.tsx
Labels: size/XS

#127 Refactor network
  src/web/app/actions/dialog-caller.tsx
  src/web/app/pages/ConnectMachineIp.tsx
  src/web/app/views/beambox/Network-Testing-Panel.tsx
  src/web/app/views/beambox/NetworkTestingPanel.spec.tsx
  src/web/app/views/beambox/NetworkTestingPanel.tsx
  src/web/app/views/beambox/__snapshots__/NetworkTestingPanel.spec.tsx.snap
  src/web/interfaces/INetwork.d.ts
Labels: size/XL

#128 Beam read/write for web
  src/web/app/actions/beambox/font-funcs.ts
  src/web/helpers/beam-file-helper.ts
  src/web/helpers/file-export-helper.ts
Labels: size/L

#129 remove electron.version which is duplicate with FLUX.version
  src/web/app/actions/beambox/menuActions.ts
  src/web/app/views/beambox/TopBar/TopBar.tsx
  src/web/app/views/dialogs/ChangeLogDialog.spec.tsx
  src/web/app/views/dialogs/ChangeLogDialog.tsx
  src/web/setupTests.ts
Labels: size/S

#130 add missing import
  src/web/app/views/beambox/TopBar/TopBar.tsx
Labels: size/XS

#132 Extract pdf helper
  src/implementations/pdfHelper.ts
  src/web/app/actions/beambox/svg-editor.ts
  src/web/helpers/api/utils-ws.ts
  src/web/helpers/pdf-helper.ts
  src/web/helpers/websocket.ts
  src/web/interfaces/IPdfHelper.d.ts
Labels: size/L

#133 Update translations
  src/web/app/lang/de.ts
  src/web/app/lang/en.ts
  src/web/app/lang/es.ts
  src/web/app/views/beambox/TopBar/Menu.spec.tsx
Labels: size/S

#134 1. simplify global interaction 2. move some actions to menu implementation
  src/web/app/actions/beambox/beambox-global-interaction.ts
  src/web/app/actions/global-interaction.ts
  src/web/helpers/electron-updater.ts
  src/web/helpers/menubar/AbstractMenu.ts
Labels: size/L

#131 split settings
  src/web/app/pages/HomeView.spec.tsx
  src/web/app/pages/HomeView.tsx
  src/web/app/pages/__snapshots__/HomeView.spec.tsx.snap
  src/web/app/views/settings/AutoSave.tsx
  src/web/app/views/settings/Camera.tsx
  src/web/app/views/settings/Connection.spec.tsx
  src/web/app/views/settings/Connection.tsx
  src/web/app/views/settings/Control.tsx
  src/web/app/views/settings/Editor.tsx
  src/web/app/views/settings/Engraving.tsx
  src/web/app/views/settings/General.spec.tsx
  src/web/app/views/settings/General.tsx
  src/web/app/views/settings/Mask.tsx
  src/web/app/views/settings/Module.tsx
  src/web/app/views/settings/Path.tsx
  src/web/app/views/settings/Privacy.tsx
  src/web/app/views/settings/SelectControl.tsx
  src/web/app/views/settings/Setting-General.tsx
  src/web/app/views/settings/SettingGeneral.tsx
  src/web/app/views/settings/TextToPath.tsx
  src/web/app/views/settings/Update.spec.tsx
  src/web/app/views/settings/Update.tsx
  src/web/app/views/settings/__snapshots__/Connection.spec.tsx.snap
  src/web/app/views/settings/__snapshots__/General.spec.tsx.snap
  src/web/app/views/settings/__snapshots__/Update.spec.tsx.snap
Labels: size/XXL

#135 Fix preset_setting translation
  src/web/app/lang/en.ts
Labels: size/XS

#136 fix location hash comparison
  src/web/app/actions/beambox/menuDeviceActions.ts
  src/web/helpers/api/flux-id.ts
  src/web/helpers/auto-save-helper.ts
  src/web/helpers/file-export-helper.ts
Labels: size/S

#137 1. fix alert popup 2. add enable/disable on top bar menu items
  src/web/app/actions/alert-caller.spec.tsx
  src/web/app/actions/alert-caller.tsx
  src/web/app/actions/progress-caller.spec.ts
  src/web/app/actions/progress-caller.ts
  src/web/app/contexts/AlertProgressContext.spec.tsx
  src/web/app/contexts/AlertProgressContext.tsx
  src/web/app/views/beambox/TopBar/Menu.spec.tsx
  src/web/app/views/beambox/TopBar/Menu.tsx
  src/web/app/views/beambox/TopBar/__snapshots__/Menu.spec.tsx.snap
  src/web/helpers/eventEmitterFactory.ts
Labels: size/L

#138 1. remove unnecessary menu item disabled
  src/web/app/views/beambox/LeftPanel/LeftPanel.tsx
  src/web/app/views/beambox/TopBar/Menu.spec.tsx
  src/web/app/views/beambox/TopBar/Menu.tsx
  src/web/app/views/beambox/TopBar/__snapshots__/Menu.spec.tsx.snap
  src/web/helpers/shortcuts.ts
  src/web/setupTests.ts
Labels: size/L

#139 remove unused extension
  public/js/lib/svgeditor/extensions/ext-shapes.js
  public/js/lib/svgeditor/extensions/ext-shapes.xml
  public/js/lib/svgeditor/svg-editor.manifest
  src/web/app/actions/beambox/svg-editor.ts
Labels: size/L

#140 Update font interface
  src/implementations/fontHelper.ts
  src/implementations/fontScanner.ts
  src/web/app/actions/beambox/font-funcs.ts
  src/web/interfaces/IFont.d.ts
Labels: size/M

#141 1. add tests 2. fix missing import
  src/web/app/actions/beambox/beambox-init.ts
  src/web/app/views/settings/AutoSave.spec.tsx
  src/web/app/views/settings/AutoSave.tsx
  src/web/app/views/settings/Camera.spec.tsx
  src/web/app/views/settings/Camera.tsx
  src/web/app/views/settings/Engraving.spec.tsx
  src/web/app/views/settings/Engraving.tsx
  src/web/app/views/settings/Mask.spec.tsx
  src/web/app/views/settings/Mask.tsx
  src/web/app/views/settings/Privacy.spec.tsx
  src/web/app/views/settings/Privacy.tsx
  src/web/app/views/settings/TextToPath.spec.tsx
  src/web/app/views/settings/TextToPath.tsx
  src/web/app/views/settings/__snapshots__/AutoSave.spec.tsx.snap
  src/web/app/views/settings/__snapshots__/Camera.spec.tsx.snap
  src/web/app/views/settings/__snapshots__/Engraving.spec.tsx.snap
  src/web/app/views/settings/__snapshots__/Mask.spec.tsx.snap
  src/web/app/views/settings/__snapshots__/Privacy.spec.tsx.snap
  src/web/app/views/settings/__snapshots__/TextToPath.spec.tsx.snap
Labels: size/XL

#142 Remove electron in home
  src/web/app/pages/Home.tsx
  src/web/helpers/api/svg-laser-parser.ts
  src/web/helpers/menubar/AbstractMenu.ts
Labels: size/M
