Repository flux3dp/beam-studio-core, pull requests merged in 2021-09, with the labels that each got.

#245 Fix dxf2svg layer parsing bug
  public/js/lib/dxf2svg.js
  src/web/app/views/beambox/Noun-Project-Panel.tsx
  src/web/app/widgets/DraggableWindow.spec.tsx
  src/web/app/widgets/DraggableWindow.tsx
  src/web/app/widgets/__snapshots__/DraggableWindow.spec.tsx.snap
  yarn.lock
Labels: size/M

#247 Fix web style
  src/web/app/components/beambox/left-panel/LeftPanel.tsx
  src/web/app/components/beambox/left-panel/__snapshots__/LeftPanel.spec.tsx.snap
  src/web/app/components/beambox/right-panel/RightPanel.tsx
  src/web/app/components/beambox/top-bar/GoButton.spec.tsx
  src/web/app/components/beambox/top-bar/GoButton.tsx
  src/web/app/components/beambox/top-bar/TopBar.tsx
  src/web/helpers/api/flux-id.ts
Labels: size/M

#248 Fix svgnest for web
  src/web/app/actions/dialog-caller.tsx
  src/web/app/views/beambox/SvgNestButtons.tsx
Labels: size/S

#249 Force login in web
  src/web/app/actions/beambox/beambox-init.ts
  src/web/app/pages/ConnectMachineIp.tsx
  src/web/app/pages/FluxIdLogin.spec.tsx
  src/web/app/pages/FluxIdLogin.tsx
  src/web/helpers/api/flux-id.ts
  src/web/helpers/social-auth.spec.ts
  src/web/helpers/social-auth.ts
Labels: size/M

#246 Support webfont for web version
  src/web/app/actions/beambox/font-funcs.ts
  src/web/app/actions/progress-caller.spec.ts
  src/web/app/actions/progress-caller.ts
  src/web/app/contexts/AlertProgressContext.tsx
  src/web/app/svgedit/svgcanvas.ts
  src/web/app/svgedit/textedit.ts
  src/web/app/views/beambox/Right-Panels/ActionsPanel.spec.tsx
  src/web/app/views/beambox/Right-Panels/ActionsPanel.tsx
  src/web/app/views/beambox/Right-Panels/Options-Blocks/TextOptions.tsx
  src/web/app/views/beambox/Right-Panels/OptionsPanel.spec.tsx
  src/web/app/views/beambox/Right-Panels/OptionsPanel.tsx
  src/web/helpers/api/utils-ws.ts
  src/web/interfaces/IFont.d.ts
Labels: size/L

#251 Fixes and updates for web
  src/web/app/actions/beambox/constant.ts
  src/web/app/actions/beambox/export-funcs.ts
  src/web/app/actions/beambox/svg-editor.ts
  src/web/app/components/beambox/path-preview/PathPreview.tsx
  src/web/app/components/beambox/top-bar/CommonTools.spec.tsx
  src/web/app/components/beambox/top-bar/CommonTools.tsx
  src/web/app/components/beambox/top-bar/PathPreviewButton.spec.tsx
  src/web/app/components/beambox/top-bar/PathPreviewButton.tsx
  src/web/app/components/beambox/top-bar/TopBar.tsx
  src/web/app/components/beambox/top-bar/__snapshots__/CommonTools.spec.tsx.snap
  src/web/app/components/beambox/top-bar/__snapshots__/PathPreviewButton.spec.tsx.snap
  src/web/app/views/beambox/Right-Panels/DimensionPanel.tsx
Labels: size/L

#252 Update media tutorial
  src/web/app/components/dialogs/MediaTutorial.spec.tsx
  src/web/app/components/dialogs/MediaTutorial.tsx
  src/web/app/constants/media-tutorials.ts
Labels: size/S

#253 Update top bar menu, add devices
  src/web/app/components/beambox/top-bar/Menu.spec.tsx
  src/web/app/components/beambox/top-bar/Menu.tsx
  src/web/app/components/beambox/top-bar/__snapshots__/Menu.spec.tsx.snap
  src/web/helpers/api/discover.ts
Labels: size/L

#254 Updates for web
  src/web/app/actions/beambox/beambox-init.ts
  src/web/app/actions/beambox/svg-editor.ts
  src/web/app/constants/font-constants.ts
  src/web/app/views/beambox/NetworkTestingPanel.tsx
Labels: size/M

#250 Feature/spectron test core
  src/web/app/components/beambox/ZoomBlock.tsx
  src/web/app/components/beambox/right-panel/LayerPanel.tsx
  src/web/app/components/settings/AutoSave.tsx
  src/web/app/components/settings/Camera.tsx
  src/web/app/components/settings/Connection.tsx
  src/web/app/components/settings/Editor.tsx
  src/web/app/components/settings/Engraving.tsx
  src/web/app/components/settings/General.tsx
  src/web/app/components/settings/Module.tsx
  src/web/app/components/settings/Path.tsx
  src/web/app/components/settings/Update.tsx
  src/web/app/components/settings/__snapshots__/AutoSave.spec.tsx.snap
  src/web/app/components/settings/__snapshots__/Camera.spec.tsx.snap
  src/web/app/components/settings/__snapshots__/Connection.spec.tsx.snap
  src/web/app/components/settings/__snapshots__/Editor.spec.tsx.snap
  src/web/app/components/settings/__snapshots__/Engraving.spec.tsx.snap
  src/web/app/components/settings/__snapshots__/General.spec.tsx.snap
  src/web/app/components/settings/__snapshots__/Update.spec.tsx.snap
  src/web/app/pages/ConnectMachineIp.tsx
  src/web/app/pages/ConnectWiFi.tsx
  src/web/app/pages/ConnectWired.tsx
  src/web/app/pages/SelectConnectionType.tsx
  src/web/app/pages/__snapshots__/ConnectWiFi.spec.tsx.snap
  src/web/app/pages/__snapshots__/ConnectWired.spec.tsx.snap
  src/web/app/pages/__snapshots__/SelectConnectionType.spec.tsx.snap
  src/web/app/views/beambox/Right-Panels/ActionsPanel.tsx
  src/web/app/views/beambox/Right-Panels/DimensionPanel.tsx
  src/web/app/views/beambox/Right-Panels/Laser-Manage-Modal.tsx
  src/web/app/views/beambox/Right-Panels/Laser-Panel.tsx
  src/web/app/views/beambox/Right-Panels/ObjectPanel.tsx
  src/web/app/views/beambox/Right-Panels/Options-Blocks/InFillBlock.tsx
  src/web/app/views/beambox/Right-Panels/Options-Blocks/TextOptions.tsx
  src/web/app/views/beambox/Right-Panels/Options-Blocks/__snapshots__/InFillBlock.spec.tsx.snap
  src/web/app/views/beambox/Right-Panels/PathEditPanel.tsx
  src/web/app/views/beambox/Right-Panels/__snapshots__/ActionsPanel.spec.tsx.snap
  src/web/app/views/beambox/Right-Panels/__snapshots__/DimensionPanel.spec.tsx.snap
  src/web/app/views/beambox/Right-Panels/__snapshots__/ObjectPanel.spec.tsx.snap
  src/web/app/views/beambox/Right-Panels/__snapshots__/PathEditPanel.spec.tsx.snap
  src/web/app/views/beambox/ToolPanels/Interval.tsx
  src/web/app/views/beambox/ToolPanels/RowColumn.tsx
  src/web/app/views/beambox/ToolPanels/__snapshots__/Interval.spec.tsx.snap
  src/web/app/views/beambox/ToolPanels/__snapshots__/RowColumn.spec.tsx.snap
  src/web/app/views/dialogs/ConfirmPrompt.tsx
  src/web/app/views/dialogs/Prompt.tsx
  src/web/app/views/dialogs/__snapshots__/ConfirmPrompt.spec.tsx.snap
  src/web/app/views/dialogs/__snapshots__/Prompt.spec.tsx.snap
  src/web/app/widgets/PathInput.tsx
  src/web/app/widgets/Progress.tsx
  src/web/app/widgets/SegmentedControl.tsx
  src/web/app/widgets/Unit-Input-v2.tsx
  src/web/app/widgets/__snapshots__/PathInput.spec.tsx.snap
Labels: size/XL

#255 Fix safari issues
  public/js/lib/svgeditor/svgutils.js
  src/web/app/svgedit/svgcanvas.ts
  src/web/app/svgedit/textactions.ts
  src/web/app/svgedit/textedit.ts
  src/web/helpers/api/utils-ws.ts
  src/web/helpers/arrayBuffer.spec.ts
  src/web/helpers/arrayBuffer.ts
  src/web/helpers/symbol-helper/image-symbol.worker.ts
Labels: size/L

#256 Update for web
  src/web/app/actions/beambox/beambox-global-interaction.ts
  src/web/app/components/beambox/TimeEstimationButton.spec.tsx
  src/web/app/components/beambox/TimeEstimationButton.tsx
  src/web/app/components/beambox/top-bar/Menu.tsx
  src/web/app/components/beambox/top-bar/TopBar.tsx
  src/web/app/components/settings/AutoSave.spec.tsx
  src/web/app/components/settings/AutoSave.tsx
  src/web/app/components/settings/Control.tsx
  src/web/app/components/settings/__snapshots__/AutoSave.spec.tsx.snap
  src/web/app/components/settings/__snapshots__/Control.spec.tsx.snap
  src/web/app/lang/de.ts
  src/web/app/lang/en.ts
  src/web/app/lang/es.ts
  src/web/app/lang/ja.ts
  src/web/app/lang/zh-cn.ts
  src/web/app/lang/zh-tw.ts
  src/web/app/pages/Beambox.tsx
  src/web/app/pages/ConnectMachineIp.tsx
  src/web/app/pages/Settings.tsx
  src/web/app/svgedit/svgcanvas.ts
  src/web/app/views/beambox/Right-Panels/ActionsPanel.spec.tsx
  src/web/app/views/beambox/Right-Panels/ActionsPanel.tsx
  src/web/helpers/check-firmware.ts
  src/web/helpers/rating-helper.ts
  src/web/helpers/version-checker.ts
  src/web/interfaces/ILang.d.ts
Labels: size/L

#257 Fix web zooming issues
  public/js/lib/svgeditor/browser.js
  src/web/app/svgedit/svgcanvas.ts
Labels: size/M

#258 Fixes for pad
  public/js/lib/svgeditor/path.js
  public/js/lib/svgeditor/touch.js
  src/web/app/actions/beambox/svg-editor.ts
  src/web/app/svgedit/selector.ts
  src/web/app/svgedit/svgcanvas.ts
  src/web/app/views/beambox/Right-Panels/DimensionPanel.tsx
Labels: size/L

#259 Fix for safari 2
  src/web/app/actions/beambox/menuActions.ts
  src/web/app/actions/beambox/svg-editor.ts
  src/web/app/actions/dialog-caller.tsx
  src/web/app/components/beambox/right-panel/ColorPickerPanel.spec.tsx
  src/web/app/components/beambox/right-panel/ColorPickerPanel.tsx
  src/web/app/components/beambox/right-panel/LayerPanel.tsx
  src/web/app/components/beambox/right-panel/__snapshots__/ColorPickerPanel.spec.tsx.snap
  src/web/app/components/dialogs/FluxIdLogin.spec.tsx
  src/web/app/components/dialogs/FluxIdLogin.tsx
  src/web/app/pages/FluxIdLogin.spec.tsx
  src/web/app/pages/FluxIdLogin.tsx
  src/web/helpers/symbol-maker.ts
Labels: size/L

#260 Add touch event delay
  src/web/app/svgedit/touchEvents.spec.tsx
  src/web/app/svgedit/touchEvents.ts
Labels: size/M

#261 Update force login in web
  src/web/app/actions/beambox/menuActions.ts
  src/web/app/actions/dialog-caller.tsx
  src/web/app/components/beambox/top-bar/GoButton.tsx
  src/web/app/components/dialogs/FluxIdLogin.tsx
  src/web/app/components/dialogs/__snapshots__/FluxIdLogin.spec.tsx.snap
  src/web/helpers/api/flux-id.ts
Labels: size/M

#262 Fix for web version and ipad
  src/web/app/actions/beambox/constant.ts
  src/web/app/components/beambox/path-preview/SidePanel.tsx
  src/web/app/components/beambox/path-preview/__snapshots__/SidePanel.spec.tsx.snap
  src/web/app/svgedit/touchEvents.spec.tsx
  src/web/app/svgedit/touchEvents.ts
Labels: size/S

#263 Fixes for web2
  public/js/lib/svgeditor/svgutils.js
  src/web/app/components/dialogs/MediaTutorial.spec.tsx
  src/web/app/components/dialogs/MediaTutorial.tsx
  src/web/app/components/dialogs/__snapshots__/MediaTutorial.spec.tsx.snap
  src/web/app/constants/media-tutorials.ts
  src/web/app/svgedit/textactions.ts
  src/web/app/svgedit/textedit.ts
  src/web/app/views/beambox/Camera-Calibration.tsx
  src/web/app/views/beambox/Right-Panels/ActionsPanel.tsx
  src/web/interfaces/ITutorial.d.ts
Labels: size/L

#264 Fix for web3
  public/js/lib/svg-nest/svgnest.js
  src/web/app/actions/beambox/constant.ts
  src/web/app/actions/beambox/tutorials.ts
  src/web/app/components/beambox/path-preview/PathPreview.tsx
  src/web/app/components/beambox/top-bar/Menu.tsx
  src/web/app/components/beambox/top-bar/__snapshots__/Menu.spec.tsx.snap
  src/web/app/components/dialogs/AboutBeamStudio.spec.tsx
  src/web/app/components/dialogs/AboutBeamStudio.tsx
  src/web/app/components/dialogs/__snapshots__/AboutBeamStudio.spec.tsx.snap
  src/web/app/constants/media-tutorials.ts
  src/web/app/constants/tutorial-constants.tsx
  src/web/app/lang/de.ts
  src/web/app/lang/en.ts
  src/web/app/lang/es.ts
  src/web/app/lang/ja.ts
  src/web/app/lang/zh-cn.ts
  src/web/app/lang/zh-tw.ts
  src/web/app/svgedit/textedit.ts
  src/web/app/views/beambox/Right-Panels/OptionsPanel.tsx
  src/web/app/views/beambox/Right-Panels/__snapshots__/OptionsPanel.spec.tsx.snap
  src/web/app/views/monitor/MonitorTask.tsx
  src/web/app/views/monitor/__snapshots__/MonitorTask.spec.tsx.snap
  src/web/app/widgets/EngraveDpiSlider.tsx
  src/web/app/widgets/__snapshots__/EngraveDpiSlider.spec.tsx.snap
  src/web/interfaces/ILang.d.ts
Labels: size/XXL

#265 Update first calibration dialog for web version
  src/web/app/actions/beambox/beambox-init.ts
  src/web/helpers/api/alert-config.ts
Labels: size/M

#266 Add error page
  src/web/app/lang/de.ts
  src/web/app/lang/en.ts
  src/web/app/lang/es.ts
  src/web/app/lang/ja.ts
  src/web/app/lang/zh-cn.ts
  src/web/app/lang/zh-tw.ts
  src/web/app/pages/Error.spec.tsx
  src/web/app/pages/Error.tsx
  src/web/app/pages/__snapshots__/Error.spec.tsx.snap
  src/web/app/router.tsx
  src/web/interfaces/ILang.d.ts
Labels: size/L

#267 Fix social auth in flux-id-login page
  src/web/helpers/social-auth.spec.ts
  src/web/helpers/social-auth.ts
Labels: size/XS
