Repository flux3dp/beam-studio-core, pull requests merged in 2021-08, with the labels that each got.

#187 add tests
  src/web/app/views/beambox/TopBar/ElementTitle.spec.tsx
  src/web/app/views/beambox/TopBar/ElementTitle.tsx
  src/web/app/views/beambox/TopBar/TopBar.tsx
  src/web/app/views/beambox/TopBar/__snapshots__/ElementTitle.spec.tsx.snap
Labels: size/L

#188 add tests
  src/web/app/views/beambox/Right-Panels/PathEditPanel.tsx
  src/web/app/views/beambox/TopBar/ElementTitle.spec.tsx
  src/web/app/views/beambox/TopBar/GoButton.spec.tsx
  src/web/app/views/beambox/TopBar/GoButton.tsx
  src/web/app/views/beambox/TopBar/TopBar.tsx
  src/web/app/views/beambox/TopBar/__snapshots__/GoButton.spec.tsx.snap
  src/web/app/widgets/Segmented-Control.tsx
  src/web/app/widgets/SegmentedControl.spec.tsx
  src/web/app/widgets/SegmentedControl.tsx
  src/web/app/widgets/__snapshots__/SegmentedControl.spec.tsx.snap
Labels: size/XXL

#189 add tests
  .github/workflows/basic-check.yml
  src/web/app/views/beambox/Right-Panels/ActionsPanel.spec.tsx
  src/web/app/views/beambox/Right-Panels/ActionsPanel.tsx
  src/web/app/views/beambox/Right-Panels/Object-Panel.tsx
  src/web/app/views/beambox/Right-Panels/__snapshots__/ActionsPanel.spec.tsx.snap
Labels: size/XL

#190 add tests
  .github/workflows/basic-check.yml
  src/web/app/svgedit/HistoryCommandFactory.ts
  src/web/app/views/beambox/Right-Panels/DimensionPanel.spec.tsx
  src/web/app/views/beambox/Right-Panels/DimensionPanel.tsx
  src/web/app/views/beambox/Right-Panels/Object-Panel.tsx
  src/web/app/views/beambox/Right-Panels/__snapshots__/DimensionPanel.spec.tsx.snap
Labels: size/XL

#191 multiple changes
  src/web/app/constants/hotkeys.ts
  src/web/app/lang/de.ts
  src/web/app/lang/en.ts
  src/web/app/lang/es.ts
  src/web/app/lang/ja.ts
  src/web/app/lang/zh-cn.ts
  src/web/app/lang/zh-tw.ts
  src/web/app/views/beambox/TopBar/Menu.spec.tsx
  src/web/app/views/beambox/TopBar/Menu.tsx
  src/web/app/views/beambox/TopBar/__snapshots__/Menu.spec.tsx.snap
  src/web/app/views/settings/General.spec.tsx
  src/web/app/views/settings/General.tsx
  src/web/app/views/settings/SettingGeneral.tsx
  src/web/app/views/settings/Update.spec.tsx
  src/web/app/views/settings/Update.tsx
  src/web/app/views/settings/__snapshots__/General.spec.tsx.snap
  src/web/app/views/settings/__snapshots__/Update.spec.tsx.snap
  src/web/interfaces/ILang.d.ts
Labels: size/L

#192 1. replace repository_dispatch with workflow_dispatch in order to specify core branch 2. remove duplicate hotkey settings
  .github/workflows/basic-check.yml
  src/web/app/constants/hotkeys.ts
Labels: size/L

#193 add undo and redo at topbar
  src/web/app/views/beambox/TopBar/CommonTools.spec.tsx
  src/web/app/views/beambox/TopBar/CommonTools.tsx
  src/web/app/views/beambox/TopBar/TopBar.tsx
  src/web/app/views/beambox/TopBar/__snapshots__/CommonTools.spec.tsx.snap
Labels: size/L

#194 enable web google oauth
  .DS_Store
  .github/workflows/basic-check.yml
  src/web/app/contexts/DialogContext.spec.tsx
  src/web/app/contexts/DialogContext.tsx
  src/web/app/contexts/__snapshots__/DialogContext.spec.tsx.snap
  src/web/app/pages/GoogleAuth.spec.tsx
  src/web/app/pages/GoogleAuth.tsx
  src/web/app/pages/__snapshots__/GoogleAuth.spec.tsx.snap
  src/web/app/router.tsx
  src/web/app/views/beambox/TopBar/Menu.spec.tsx
  src/web/app/views/beambox/TopBar/Menu.tsx
  src/web/app/views/beambox/TopBar/TopBar.tsx
  src/web/app/views/beambox/TopBar/__snapshots__/Menu.spec.tsx.snap
  src/web/app/views/beambox/TopBar/contexts/TopBarContext.tsx
  src/web/helpers/api/flux-id.ts
Labels: size/XXL

#195 enable flux id login
  src/web/helpers/api/flux-id.ts
Labels: size/S

#199 Update svg nest buttons classname
  src/web/app/views/beambox/Svg-Nest-Buttons.tsx
Labels: size/XS

#200 Update import image, using dialog
  src/web/app/actions/beambox/menuActions.ts
  src/web/app/actions/beambox/svgeditor-function-wrapper.ts
  src/web/app/views/beambox/LeftPanel/LeftPanel.tsx
  src/web/setupTests.ts
Labels: size/L

#198 Path preview
  package.json
  src/web/app/actions/beambox/export-funcs.ts
  src/web/app/actions/beambox/preview-mode-background-drawer.ts
  src/web/app/actions/monitor-controller.tsx
  src/web/app/contexts/Monitor-Context.tsx
  src/web/app/pages/Beambox.tsx
  src/web/app/pages/__snapshots__/svg-editor.spec.tsx.snap
  src/web/app/pages/svg-editor.spec.tsx
  src/web/app/pages/svg-editor.tsx
  src/web/app/svgedit/svgcanvas.ts
  src/web/app/views/beambox/DocumentPanel/DocumentPanel.tsx
  src/web/app/views/beambox/DocumentPanel/__snapshots__/DocumentPanel.spec.tsx.snap
  src/web/app/views/beambox/LeftPanel/LeftPanel.spec.tsx
  src/web/app/views/beambox/LeftPanel/LeftPanel.tsx
  src/web/app/views/beambox/LeftPanel/__snapshots__/LeftPanel.spec.tsx.snap
  src/web/app/views/beambox/Path-Preview.tsx
  src/web/app/views/beambox/PathPreview/SidePanel.tsx
  src/web/app/views/beambox/Pointable.tsx
  src/web/app/views/beambox/TopBar/TopBar.tsx
  src/web/app/views/beambox/ZoomBlock/ZoomBlock.tsx
  src/web/app/views/beambox/ZoomBlock/ZoomBlockController.spec.tsx
  src/web/app/views/beambox/ZoomBlock/ZoomBlockController.tsx
  src/web/app/views/beambox/ZoomBlock/contexts/ZoomBlockContext.spec.tsx
  src/web/app/views/beambox/ZoomBlock/contexts/ZoomBlockContext.tsx
  src/web/app/views/beambox/dom3d.tsx
  src/web/app/views/beambox/tmpParseGcode.js
  src/web/helpers/api/svg-laser-parser.ts
  src/web/helpers/check-webgl.ts
  src/web/helpers/eventEmitterFactory.ts
  src/web/helpers/path-preview/draw-commands/GcodePreview.js
  src/web/helpers/path-preview/draw-commands/basic.js
  src/web/helpers/path-preview/draw-commands/image.js
  src/web/helpers/path-preview/draw-commands/imageMesh.js
  src/web/helpers/path-preview/draw-commands/index.js
  src/web/helpers/path-preview/draw-commands/thick-lines.js
  src/web/helpers/path-preview/draw-commands/webcam.js
  src/web/helpers/path-preview/draw-commands/webcamfx.js
  src/web/helpers/units.ts
  yarn.lock
Labels: size/XXL

#201 add a new option used to control the sides of polygon
  public/js/lib/svgeditor/extensions/ext-polygon.js
  src/web/app/actions/beambox/svg-editor.ts
  src/web/app/lang/de.ts
  src/web/app/lang/en.ts
  src/web/app/lang/es.ts
  src/web/app/lang/ja.ts
  src/web/app/lang/zh-cn.ts
  src/web/app/lang/zh-tw.ts
  src/web/app/views/beambox/Right-Panels/ObjectPanel.tsx
  src/web/app/views/beambox/Right-Panels/Options-Blocks/PolygonOptions.spec.tsx
  src/web/app/views/beambox/Right-Panels/Options-Blocks/PolygonOptions.tsx
  src/web/app/views/beambox/Right-Panels/Options-Blocks/__snapshots__/PolygonOptions.spec.tsx.snap
  src/web/app/views/beambox/Right-Panels/OptionsPanel.spec.tsx
  src/web/app/views/beambox/Right-Panels/OptionsPanel.tsx
  src/web/app/views/beambox/Right-Panels/__snapshots__/OptionsPanel.spec.tsx.snap
  src/web/app/views/beambox/Right-Panels/contexts/ObjectPanelContext.tsx
  src/web/app/views/beambox/Right-Panels/contexts/ObjectPanelController.spec.tsx
  src/web/app/views/beambox/Right-Panels/contexts/ObjectPanelController.tsx
  src/web/interfaces/ILang.d.ts
  src/web/setupTests.ts
Labels: size/L

#203 Add i18n
  src/web/app/lang/de.ts
  src/web/app/lang/en.ts
  src/web/app/lang/es.ts
  src/web/app/lang/ja.ts
  src/web/app/lang/zh-cn.ts
  src/web/app/lang/zh-tw.ts
  src/web/app/views/beambox/Path-Preview.tsx
  src/web/app/views/beambox/PathPreview/SidePanel.tsx
  src/web/helpers/websocket.ts
  src/web/interfaces/ILang.d.ts
Labels: size/L

#204 Fix path preview related bug
  src/web/app/pages/Beambox.tsx
  src/web/app/views/beambox/Path-Preview.tsx
  src/web/app/views/beambox/TopBar/TopBar.tsx
Labels: size/M

#202 add tests
  .github/workflows/basic-check.yml
  src/web/app/views/beambox/Right-Panels/ObjectPanel.spec.tsx
  src/web/app/views/beambox/Right-Panels/ObjectPanel.tsx
  src/web/app/views/beambox/Right-Panels/__snapshots__/ObjectPanel.spec.tsx.snap
Labels: size/XXL

#205 Fix unable to type after path preview merged
  src/web/app/pages/__snapshots__/svg-editor.spec.tsx.snap
  src/web/app/pages/svg-editor.tsx
Labels: size/XXL

#206 add SidePanel test
  .github/workflows/basic-check.yml
  src/web/app/views/beambox/PathPreview/SidePanel.spec.tsx
  src/web/app/views/beambox/PathPreview/SidePanel.tsx
  src/web/app/views/beambox/PathPreview/__snapshots__/SidePanel.spec.tsx.snap
  src/web/app/views/beambox/dom3d.tsx
Labels: size/L

#207 hide skip button for web users
  .github/workflows/basic-check.yml
  src/web/app/pages/FluxIdLogin.tsx
  src/web/app/views/FluxIdLogin.spec.tsx
  src/web/app/views/FluxIdLogin.tsx
  src/web/app/views/__snapshots__/FluxIdLogin.spec.tsx.snap
Labels: size/L

#208 minor reorg
  .github/workflows/basic-check.yml
  src/web/app/actions/dialog-caller.tsx
  src/web/app/app-settings.ts
  src/web/app/components/beambox/SvgEditor.spec.tsx
  src/web/app/components/beambox/SvgEditor.tsx
  src/web/app/components/beambox/ZoomBlock.tsx
  src/web/app/components/beambox/__snapshots__/SvgEditor.spec.tsx.snap
  src/web/app/components/beambox/path-preview/PathPreview.tsx
  src/web/app/components/beambox/path-preview/Pointable.tsx
  src/web/app/components/beambox/path-preview/ProgressBar.spec.tsx
  src/web/app/components/beambox/path-preview/ProgressBar.tsx
  src/web/app/components/beambox/path-preview/SidePanel.spec.tsx
  src/web/app/components/beambox/path-preview/SidePanel.tsx
  src/web/app/components/beambox/path-preview/__snapshots__/ProgressBar.spec.tsx.snap
  src/web/app/components/beambox/path-preview/__snapshots__/SidePanel.spec.tsx.snap
  src/web/app/components/dialogs/AboutBeamStudio.spec.tsx
  src/web/app/components/dialogs/AboutBeamStudio.tsx
  src/web/app/components/dialogs/ChangeLog.spec.tsx
  src/web/app/components/dialogs/ChangeLog.tsx
  src/web/app/components/dialogs/FluxIdLogin.spec.tsx
  src/web/app/components/dialogs/FluxIdLogin.tsx
  src/web/app/components/dialogs/RatingPanel.spec.tsx
  src/web/app/components/dialogs/RatingPanel.tsx
  src/web/app/components/dialogs/__snapshots__/AboutBeamStudio.spec.tsx.snap
  src/web/app/components/dialogs/__snapshots__/ChangeLog.spec.tsx.snap
  src/web/app/components/dialogs/__snapshots__/FluxIdLogin.spec.tsx.snap
  src/web/app/components/dialogs/__snapshots__/RatingPanel.spec.tsx.snap
  src/web/app/pages/Beambox.tsx
  src/web/app/pages/FacebookOAuth.spec.tsx
  src/web/app/pages/FacebookOAuth.tsx
  src/web/app/pages/GoogleOAuth.spec.tsx
  src/web/app/pages/GoogleOAuth.tsx
  src/web/app/pages/Select-Machine-Type.spec.tsx
  src/web/app/pages/Select-Machine-Type.tsx
  src/web/app/pages/__snapshots__/FacebookOAuth.spec.tsx.snap
  src/web/app/pages/__snapshots__/GoogleOAuth.spec.tsx.snap
  src/web/app/pages/__snapshots__/Select-Machine-Type.spec.tsx.snap
  src/web/app/router.tsx
  src/web/app/svgedit/svgcanvas.ts
  src/web/app/views/beambox/ZoomBlock/ZoomBlockController.spec.tsx
  src/web/app/views/beambox/ZoomBlock/ZoomBlockController.tsx
  src/web/helpers/eventEmitterFactory.ts
Labels: size/L

#211 Fix path preview
  src/web/app/components/beambox/path-preview/PathPreview.tsx
  src/web/app/views/beambox/TopBar/TopBar.tsx
Labels: size/M

#209 minor reorg 2
  .github/workflows/basic-check.yml
  src/web/app/actions/dialog-caller.tsx
  src/web/app/components/beambox/top-bar/TopBar.tsx
  src/web/app/components/dialogs/FirmwareUpdate.spec.tsx
  src/web/app/components/dialogs/FirmwareUpdate.tsx
  src/web/app/components/dialogs/__snapshots__/FirmwareUpdate.spec.tsx.snap
  src/web/app/components/settings/AutoSave.spec.tsx
  src/web/app/components/settings/AutoSave.tsx
  src/web/app/components/settings/Camera.spec.tsx
  src/web/app/components/settings/Camera.tsx
  src/web/app/components/settings/Connection.spec.tsx
  src/web/app/components/settings/Connection.tsx
  src/web/app/components/settings/Control.spec.tsx
  src/web/app/components/settings/Control.tsx
  src/web/app/components/settings/Editor.spec.tsx
  src/web/app/components/settings/Editor.tsx
  src/web/app/components/settings/Engraving.spec.tsx
  src/web/app/components/settings/Engraving.tsx
  src/web/app/components/settings/General.spec.tsx
  src/web/app/components/settings/General.tsx
  src/web/app/components/settings/Mask.spec.tsx
  src/web/app/components/settings/Mask.tsx
  src/web/app/components/settings/Module.tsx
  src/web/app/components/settings/Path.tsx
  src/web/app/components/settings/Privacy.spec.tsx
  src/web/app/components/settings/Privacy.tsx
  src/web/app/components/settings/SelectControl.tsx
  src/web/app/components/settings/TextToPath.spec.tsx
  src/web/app/components/settings/TextToPath.tsx
  src/web/app/components/settings/Update.spec.tsx
  src/web/app/components/settings/Update.tsx
  src/web/app/components/settings/__snapshots__/AutoSave.spec.tsx.snap
  src/web/app/components/settings/__snapshots__/Camera.spec.tsx.snap
  src/web/app/components/settings/__snapshots__/Connection.spec.tsx.snap
  src/web/app/components/settings/__snapshots__/Control.spec.tsx.snap
  src/web/app/components/settings/__snapshots__/Editor.spec.tsx.snap
  src/web/app/components/settings/__snapshots__/Engraving.spec.tsx.snap
  src/web/app/components/settings/__snapshots__/General.spec.tsx.snap
  src/web/app/components/settings/__snapshots__/Mask.spec.tsx.snap
  src/web/app/components/settings/__snapshots__/Privacy.spec.tsx.snap
  src/web/app/components/settings/__snapshots__/TextToPath.spec.tsx.snap
  src/web/app/components/settings/__snapshots__/Update.spec.tsx.snap
  src/web/app/pages/Beambox.tsx
  src/web/app/pages/HomeView.spec.tsx
  src/web/app/pages/HomeView.tsx
  src/web/app/pages/Settings.tsx
  src/web/app/pages/__snapshots__/HomeView.spec.tsx.snap
  src/web/app/router.tsx
  src/web/app/views/beambox/TopBar/ElementTitle.spec.tsx
  src/web/app/views/beambox/TopBar/__snapshots__/ElementTitle.spec.tsx.snap
  src/web/helpers/firmware-updater.ts
  src/web/helpers/path-preview/draw-commands/webcam.js
Labels: size/XL

#210 minor reorg 3
  .github/workflows/basic-check.yml
  src/web/app/components/beambox/top-bar/CommonTools.spec.tsx
  src/web/app/components/beambox/top-bar/CommonTools.tsx
  src/web/app/components/beambox/top-bar/ElementTitle.spec.tsx
  src/web/app/components/beambox/top-bar/ElementTitle.tsx
  src/web/app/components/beambox/top-bar/FileName.spec.tsx
  src/web/app/components/beambox/top-bar/FileName.tsx
  src/web/app/components/beambox/top-bar/GoButton.spec.tsx
  src/web/app/components/beambox/top-bar/GoButton.tsx
  src/web/app/components/beambox/top-bar/Menu.spec.tsx
  src/web/app/components/beambox/top-bar/Menu.tsx
  src/web/app/components/beambox/top-bar/TopBar.tsx
  src/web/app/components/beambox/top-bar/TopBarHints.spec.tsx
  src/web/app/components/beambox/top-bar/TopBarHints.tsx
  src/web/app/components/beambox/top-bar/__snapshots__/CommonTools.spec.tsx.snap
  src/web/app/components/beambox/top-bar/__snapshots__/ElementTitle.spec.tsx.snap
  src/web/app/components/beambox/top-bar/__snapshots__/FileName.spec.tsx.snap
  src/web/app/components/beambox/top-bar/__snapshots__/GoButton.spec.tsx.snap
  src/web/app/components/beambox/top-bar/__snapshots__/Menu.spec.tsx.snap
  src/web/app/components/beambox/top-bar/__snapshots__/TopBarHints.spec.tsx.snap
  src/web/app/contexts/TopBarContext.spec.tsx
  src/web/app/contexts/TopBarContext.tsx
  src/web/app/contexts/TopBarHintsContext.spec.tsx
  src/web/app/contexts/TopBarHintsContext.tsx
  src/web/app/pages/Beambox.tsx
  src/web/app/views/beambox/LeftPanel/PreviewToolButtonGroup.spec.tsx
  src/web/app/views/beambox/LeftPanel/__snapshots__/PreviewToolButtonGroup.spec.tsx.snap
Labels: size/L

#212 Disable path preview button when path previewing
  src/web/app/components/beambox/top-bar/TopBar.tsx
Labels: size/XS

#214 merge unit test with coverage check
  .github/workflows/basic-check.yml
Labels: size/S

#215 Fix textpath
  src/web/app/lang/de.ts
  src/web/app/lang/en.ts
  src/web/app/lang/es.ts
  src/web/app/lang/ja.ts
  src/web/app/lang/zh-cn.ts
  src/web/app/lang/zh-tw.ts
  src/web/app/svgedit/svgcanvas.ts
  src/web/app/views/beambox/Right-Panels/ActionsPanel.tsx
  src/web/app/views/beambox/Right-Panels/Options-Blocks/TextOptions/StartOffsetBlock.spec.tsx
  src/web/app/views/beambox/Right-Panels/Options-Blocks/TextOptions/__snapshots__/StartOffsetBlock.spec.tsx.snap
Labels: size/M

#216 in web, should show #801 error while doing path-preview without device connection
  .github/workflows/basic-check.yml
  src/web/app/components/beambox/top-bar/PathPreviewButton.spec.tsx
  src/web/app/components/beambox/top-bar/PathPreviewButton.tsx
  src/web/app/components/beambox/top-bar/TopBar.tsx
  src/web/app/components/beambox/top-bar/__snapshots__/PathPreviewButton.spec.tsx.snap
Labels: size/L

#217 Add canvas touch events
  src/web/app/svgedit/__snapshots__/touchEvents.spec.tsx.snap
  src/web/app/svgedit/svgcanvas.ts
  src/web/app/svgedit/touchEvents.spec.tsx
  src/web/app/svgedit/touchEvents.ts
Labels: size/XL

#218 Fix 1.8.0
  src/web/app/components/beambox/path-preview/PathPreview.tsx
  src/web/app/svgedit/svgcanvas.ts
Labels: size/XS

#219 extract PreviewButton
  src/web/app/components/beambox/top-bar/PreviewButton.spec.tsx
  src/web/app/components/beambox/top-bar/PreviewButton.tsx
  src/web/app/components/beambox/top-bar/TopBar.tsx
  src/web/app/components/beambox/top-bar/__snapshots__/PreviewButton.spec.tsx.snap
Labels: size/L

#220 Fix path preview image starting path issue
  src/web/app/components/beambox/path-preview/PathPreview.tsx
Labels: size/XS

#221 Fix exporting issue when using start here at 0:00
  src/web/app/components/beambox/path-preview/PathPreview.tsx
Labels: size/S

#223 Remove PathPreview redundant lines
  src/web/app/components/beambox/path-preview/PathPreview.tsx
Labels: size/M

#222 1. minor reorg 2. add tests
  .github/workflows/basic-check.yml
  src/web/app/components/beambox/left-panel/DrawingToolButtonGroup.spec.tsx
  src/web/app/components/beambox/left-panel/DrawingToolButtonGroup.tsx
  src/web/app/components/beambox/left-panel/LeftPanel.spec.tsx
  src/web/app/components/beambox/left-panel/LeftPanel.tsx
  src/web/app/components/beambox/left-panel/PreviewToolButtonGroup.spec.tsx
  src/web/app/components/beambox/left-panel/PreviewToolButtonGroup.tsx
  src/web/app/components/beambox/left-panel/__snapshots__/DrawingToolButtonGroup.spec.tsx.snap
  src/web/app/components/beambox/left-panel/__snapshots__/LeftPanel.spec.tsx.snap
  src/web/app/components/beambox/left-panel/__snapshots__/PreviewToolButtonGroup.spec.tsx.snap
  src/web/app/components/beambox/top-bar/TopBar.tsx
  src/web/app/contexts/TopBarLeftPanelContext.spec.tsx
  src/web/app/contexts/TopBarLeftPanelContext.tsx
  src/web/app/pages/Beambox.tsx
  src/web/app/views/beambox/LeftPanel/LeftPanel.spec.tsx
  src/web/app/views/beambox/LeftPanel/__snapshots__/LeftPanel.spec.tsx.snap
Labels: size/XL

#224 move duplicate code endPreviewMode from LeftPanel and TopBar to Context layer
  .github/workflows/basic-check.yml
  src/web/app/components/beambox/left-panel/LeftPanel.spec.tsx
  src/web/app/components/beambox/left-panel/LeftPanel.tsx
  src/web/app/components/beambox/left-panel/__snapshots__/LeftPanel.spec.tsx.snap
  src/web/app/components/beambox/top-bar/TopBar.tsx
  src/web/app/contexts/TopBarLeftPanelContext.spec.tsx
  src/web/app/contexts/TopBarLeftPanelContext.tsx
Labels: size/L

#225 Update canvas context menu
  package.json
  public/js/lib/svgeditor/contextmenu/jquery.contextMenu.js
  src/web/app/actions/beambox/svg-editor.ts
  src/web/app/components/beambox/SvgEditor.spec.tsx
  src/web/app/components/beambox/SvgEditor.tsx
  src/web/app/components/beambox/Workarea.spec.tsx
  src/web/app/components/beambox/Workarea.tsx
  src/web/app/components/beambox/ZoomBlock.tsx
  src/web/app/components/beambox/__snapshots__/SvgEditor.spec.tsx.snap
  src/web/app/components/beambox/__snapshots__/Workarea.spec.tsx.snap
  src/web/app/components/beambox/top-bar/PreviewButton.tsx
  src/web/app/contexts/TopBarLeftPanelContext.spec.tsx
  src/web/app/contexts/TopBarLeftPanelContext.tsx
  src/web/app/views/beambox/Right-Panels/LayerPanel.tsx
  src/web/helpers/eventEmitterFactory.ts
  src/web/helpers/firmware-updater.ts
  src/web/helpers/react-contextmenu/AbstractMenu.tsx
  src/web/helpers/react-contextmenu/ContextMenu.spec.tsx
  src/web/helpers/react-contextmenu/ContextMenu.tsx
  src/web/helpers/react-contextmenu/ContextMenuTrigger.tsx
  src/web/helpers/react-contextmenu/LICENSE.md
  src/web/helpers/react-contextmenu/MenuItem.spec.tsx
  src/web/helpers/react-contextmenu/MenuItem.tsx
  src/web/helpers/react-contextmenu/SubMenu.spec.tsx
  src/web/helpers/react-contextmenu/SubMenu.tsx
  src/web/helpers/react-contextmenu/__snapshots__/ContextMenu.spec.tsx.snap
  src/web/helpers/react-contextmenu/__snapshots__/MenuItem.spec.tsx.snap
  src/web/helpers/react-contextmenu/__snapshots__/SubMenu.spec.tsx.snap
  src/web/helpers/react-contextmenu/actions.spec.ts
  src/web/helpers/react-contextmenu/actions.ts
  src/web/helpers/react-contextmenu/connectMenu.tsx
  src/web/helpers/react-contextmenu/globalEventListener.tsx
  src/web/helpers/react-contextmenu/helpers.ts
  src/web/helpers/react-contextmenu/index.ts
  yarn.lock
Labels: size/XXL

#226 minor reorg
  .github/workflows/basic-check.yml
  src/web/app/actions/dialog-caller.tsx
  src/web/app/components/beambox/SvgEditor.spec.tsx
  src/web/app/components/beambox/SvgEditor.tsx
  src/web/app/components/beambox/TimeEstimationButton.spec.tsx
  src/web/app/components/beambox/TimeEstimationButton.tsx
  src/web/app/components/beambox/__snapshots__/SvgEditor.spec.tsx.snap
  src/web/app/components/beambox/__snapshots__/TimeEstimationButton.spec.tsx.snap
  src/web/app/components/dialogs/DocumentSettings.spec.tsx
  src/web/app/components/dialogs/DocumentSettings.tsx
  src/web/app/components/dialogs/__snapshots__/DocumentSettings.spec.tsx.snap
  src/web/app/contexts/TimeEstimationButtonContext.spec.tsx
  src/web/app/contexts/TimeEstimationButtonContext.tsx
  src/web/app/pages/Beambox.tsx
  src/web/app/svgedit/svgcanvas.ts
  src/web/app/views/beambox/Right-Panels/Laser-Panel.tsx
  src/web/app/views/beambox/TimeEstimationButton/TimeEstimationButtonController.spec.ts
  src/web/app/views/beambox/TimeEstimationButton/TimeEstimationButtonController.ts
Labels: size/L

#227 Fix textaction curtext type
  src/web/app/svgedit/textactions.ts
  src/web/helpers/react-contextmenu/ContextMenuTrigger.tsx
Labels: size/XS

#229 Add bb2 argument
  src/web/helpers/api/svg-laser-parser.ts
Labels: size/XS

#228 Fix alert event emit before registered
  src/web/app/actions/alert-caller.spec.tsx
  src/web/app/actions/alert-caller.tsx
  src/web/app/pages/Beambox.tsx
Labels: size/S

#231 Fix importImage extensions
  src/web/app/actions/beambox/svgeditor-function-wrapper.ts
Labels: size/XS

#230 minor reorg on RightPanel
  .github/workflows/basic-check.yml
  src/web/app/components/beambox/right-panel/AddLayerButton.tsx
  src/web/app/components/beambox/right-panel/ColorPickerPanel.spec.tsx
  src/web/app/components/beambox/right-panel/ColorPickerPanel.tsx
  src/web/app/components/beambox/right-panel/DragImage.tsx
  src/web/app/components/beambox/right-panel/LayerPanel.tsx
  src/web/app/components/beambox/right-panel/RightPanel.tsx
  src/web/app/components/beambox/right-panel/SelLayerBlock.tsx
  src/web/app/components/beambox/right-panel/Tab.spec.tsx
  src/web/app/components/beambox/right-panel/Tab.tsx
  src/web/app/components/beambox/right-panel/__snapshots__/ColorPickerPanel.spec.tsx.snap
  src/web/app/components/beambox/right-panel/__snapshots__/Tab.spec.tsx.snap
  src/web/app/pages/Beambox.tsx
  src/web/app/views/beambox/Right-Panels/Right-Panel.tsx
Labels: size/XXL

#233 Add layer panel touch behaviors
  .github/workflows/basic-check.yml
  src/web/app/components/beambox/right-panel/LayerPanel.tsx
  src/web/helpers/react-contextmenu/ContextMenuTrigger.tsx
Labels: size/L

#234 Add path & text edit for touch
  package.json
  src/web/app/svgedit/svgcanvas.ts
  src/web/app/svgedit/textactions.ts
  src/web/app/svgedit/touchEvents.spec.tsx
  src/web/app/svgedit/touchEvents.ts
  yarn.lock
Labels: size/M

#235 Fix recalculate.js for transformed path
  public/js/lib/svgeditor/recalculate.js
Labels: size/M

#236 Add delete to common tools
  src/web/app/components/beambox/top-bar/CommonTools.spec.tsx
  src/web/app/components/beambox/top-bar/CommonTools.tsx
  src/web/app/components/beambox/top-bar/__snapshots__/CommonTools.spec.tsx.snap
Labels: size/M

#237 Use mock fast gradient gcode to get correct previewing path
  src/web/app/actions/beambox/export-funcs.ts
  src/web/app/components/beambox/path-preview/PathPreview.tsx
  src/web/helpers/api/svg-laser-parser.ts
Labels: size/XS

#239 Apply accelerate adjustment to path preview
  src/web/helpers/path-preview/draw-commands/GcodePreview.js
Labels: size/L

#240 Add media tutorial
  src/web/app/actions/beambox/beambox-init.ts
  src/web/app/actions/beambox/menuActions.ts
  src/web/app/actions/dialog-caller.tsx
  src/web/app/components/beambox/top-bar/Menu.spec.tsx
  src/web/app/components/beambox/top-bar/Menu.tsx
  src/web/app/components/beambox/top-bar/__snapshots__/Menu.spec.tsx.snap
  src/web/app/components/dialogs/MediaTutorial.spec.tsx
  src/web/app/components/dialogs/MediaTutorial.tsx
  src/web/app/components/dialogs/__snapshots__/MediaTutorial.spec.tsx.snap
  src/web/app/constants/media-tutorials.ts
  src/web/app/lang/de.ts
  src/web/app/lang/en.ts
  src/web/app/lang/es.ts
  src/web/app/lang/ja.ts
  src/web/app/lang/zh-cn.ts
  src/web/app/lang/zh-tw.ts
  src/web/app/svgedit/svgcanvas.ts
  src/web/helpers/api/flux-id.ts
  src/web/interfaces/ILang.d.ts
  src/web/interfaces/ITutorial.d.ts
Labels: size/XXL

#241 Disable start here when playing
  src/web/app/components/beambox/path-preview/PathPreview.tsx
  src/web/app/components/beambox/path-preview/SidePanel.spec.tsx
  src/web/app/components/beambox/path-preview/SidePanel.tsx
  src/web/app/components/beambox/path-preview/__snapshots__/SidePanel.spec.tsx.snap
Labels: size/L
