Repository flux3dp/beam-studio-core, pull requests merged in 2021-07, with the labels that each got.

#143 fix the issue that touch is not working in tablet/mobile
  public/js/lib/svgeditor/touch.js
Labels: size/XS

#144 Update flux api for web
  src/web/app/views/FluxIdLogin.tsx
  src/web/app/views/beambox/Camera-Calibration.tsx
  src/web/app/views/beambox/Diode-Calibration.tsx
  src/web/helpers/api/flux-id.ts
  src/web/helpers/check-device-status.ts
  src/web/helpers/symbol-maker.ts
Labels: size/L

#145 move preventDefault to svg only to avoid triggering multiple events
  public/js/lib/svgeditor/touch.js
  src/web/app/actions/beambox/svgeditor-function-wrapper.ts
Labels: size/XS

#146 Fix minor bugs
  src/web/app/svgedit/svgcanvas.ts
  src/web/helpers/file-export-helper.ts
Labels: size/S

#147 move checkOSVersion out
  src/implementations/beamboxInit.ts
  src/web/app/actions/beambox/beambox-init.ts
  src/web/app/pages/Beambox.tsx
Labels: size/XL

#150 delete Task-Interpreter-Panel.tsx
  src/web/app/actions/beambox/export-funcs.ts
  src/web/app/pages/svg-editor.spec.tsx
  src/web/app/views/beambox/Task-Interpreter-Panel.tsx
  src/web/app/widgets/Vertical-Slider-Control.tsx
Labels: size/XXL

#151 Fix 1.7.1 bugs
  public/js/lib/svgeditor/select.js
  src/web/app/lang/de.ts
  src/web/app/lang/en.ts
  src/web/app/lang/es.ts
  src/web/app/lang/ja.ts
  src/web/app/lang/zh-cn.ts
  src/web/app/lang/zh-tw.ts
  src/web/app/svgedit/svgcanvas.ts
Labels: size/S

#153 Fix photo crop output size
  src/web/app/views/beambox/Photo-Edit-Panel.tsx
Labels: size/S

#152 fix positive lookbehind
  src/web/app/actions/beambox/font-funcs.ts
  src/web/app/svgedit/svgcanvas.ts
  src/web/app/views/beambox/ZoomBlock/ZoomBlock.tsx
Labels: size/S

#154 fix negative lookbehind
  src/web/app/views/beambox/Layer-Color-Config.tsx
Labels: size/XS

#148 add tests
  src/web/app/pages/Home.spec.tsx
  src/web/app/pages/Home.tsx
  src/web/app/pages/__snapshots__/Home.spec.tsx.snap
  src/web/app/views/settings/AutoSave.spec.tsx
  src/web/app/views/settings/Control.spec.tsx
  src/web/app/views/settings/Editor.spec.tsx
  src/web/app/views/settings/Editor.tsx
  src/web/app/views/settings/__snapshots__/AutoSave.spec.tsx.snap
  src/web/app/views/settings/__snapshots__/Control.spec.tsx.snap
  src/web/app/views/settings/__snapshots__/Editor.spec.tsx.snap
Labels: size/XXL

#156 Update sentry interface
  src/web/helpers/sentry-helper.ts
Labels: size/XS

#155 add tests
  src/web/app/actions/beambox/font-funcs.ts
  src/web/app/actions/dialog-caller.tsx
  src/web/app/views/beambox/DocumentPanel/DocumentPanel.spec.tsx
  src/web/app/views/beambox/DocumentPanel/DocumentPanel.tsx
  src/web/app/views/beambox/DocumentPanel/__snapshots__/DocumentPanel.spec.tsx.snap
  src/web/app/views/beambox/Right-Panels/Laser-Panel.tsx
  src/web/app/widgets/Dropdown-Control.tsx
  src/web/app/widgets/EngraveDpiSlider.tsx
  src/web/app/widgets/Switch-Control.spec.tsx
  src/web/app/widgets/Switch-Control.tsx
  src/web/app/widgets/__snapshots__/Switch-Control.spec.tsx.snap
Labels: size/XL

#157 Refactor select.js to selector.ts
  public/js/lib/svgeditor/select.js
  src/web/app/svgedit/canvasBackground.ts
  src/web/app/svgedit/operations/clipboard.ts
  src/web/app/svgedit/operations/delete.ts
  src/web/app/svgedit/selector.ts
  src/web/app/svgedit/svgcanvas.ts
  src/web/app/svgedit/textactions.ts
  src/web/app/svgedit/textedit.ts
Labels: size/XXL

#158 fix the remaining positive lookbehind
  src/web/app/views/beambox/ZoomBlock/ZoomBlock.tsx
Labels: size/S

#159 Fix config of layers created in appendUseElement
  src/web/app/svgedit/svgcanvas.ts
Labels: size/XS

#160 add tests
  src/web/app/views/beambox/Right-Panels/Options-Blocks/InFillBlock.spec.tsx
  src/web/app/views/beambox/Right-Panels/Options-Blocks/InFillBlock.tsx
  src/web/app/views/beambox/Right-Panels/Options-Blocks/Infill-Block.tsx
  src/web/app/views/beambox/Right-Panels/Options-Blocks/RectOptions.spec.tsx
  src/web/app/views/beambox/Right-Panels/Options-Blocks/RectOptions.tsx
  src/web/app/views/beambox/Right-Panels/Options-Blocks/Text-Options.tsx
  src/web/app/views/beambox/Right-Panels/Options-Blocks/__snapshots__/InFillBlock.spec.tsx.snap
  src/web/app/views/beambox/Right-Panels/Options-Blocks/__snapshots__/RectOptions.spec.tsx.snap
  src/web/app/views/beambox/Right-Panels/Options-Panel.tsx
Labels: size/XL

#161 Seperate move out
  src/web/app/actions/beambox/font-funcs.ts
  src/web/app/actions/beambox/svg-editor.ts
  src/web/app/svgedit/history.ts
  src/web/app/svgedit/operations/clipboard.ts
  src/web/app/svgedit/operations/move.ts
  src/web/app/svgedit/selector.ts
  src/web/app/svgedit/svgcanvas.ts
  src/web/app/views/beambox/Image-Trace-Panel.tsx
Labels: size/L

#162 trigger web workflow once the core has a new commit merged into master
  .github/workflows/basic-check.yml
  .github/workflows/repository-dispatch.yml
Labels: size/S

#163 add the remaining menu items
  src/web/app/views/beambox/TopBar/Menu.tsx
  src/web/app/views/beambox/TopBar/__snapshots__/Menu.spec.tsx.snap
Labels: size/L

#164 Fix undo/redo related bugs
  src/web/app/svgedit/history.ts
  src/web/app/svgedit/svgcanvas.ts
Labels: size/S

#165 Bx1.7.1 12
  src/web/app/lang/de.ts
  src/web/app/lang/en.ts
  src/web/app/lang/es.ts
  src/web/app/lang/ja.ts
  src/web/app/views/beambox/TopBar/Menu.spec.tsx
Labels: size/M

#166 wait until the remote workflow's job is done and return result
  .github/workflows/repository-dispatch.yml
Labels: size/S

#167 add tests
  .github/workflows/basic-check.yml
  jest.config.js
  src/web/helpers/sentry-helper.spec.ts
  src/web/helpers/sentry-helper.ts
  src/web/helpers/shortcuts.ts
  src/web/helpers/units.spec.ts
  src/web/helpers/version-checker.spec.ts
  src/web/helpers/version-checker.ts
  src/web/helpers/websocket.ts
Labels: size/L

#168 add tests
  .github/workflows/basic-check.yml
  src/web/helpers/laser-config-helper.spec.ts
  src/web/helpers/laser-config-helper.ts
  src/web/helpers/logger.spec.ts
  src/web/helpers/logger.ts
  src/web/helpers/query-data-parser.spec.ts
  src/web/helpers/query-data-parser.ts
  src/web/helpers/rating-helper.spec.ts
  src/web/helpers/rating-helper.ts
Labels: size/L

#169 Add diode calibration with calibration mode cmd
  src/web/app/constants/device-constants.ts
  src/web/helpers/device-master.ts
  src/web/helpers/version-checker.ts
Labels: size/S

#170 remove unused file
  src/web/helpers/jquery.box.ts
Labels: size/S

#171 add tests
  .github/workflows/basic-check.yml
  src/web/helpers/global-helper.spec.ts
  src/web/helpers/grayscale.spec.ts
  src/web/helpers/grayscale.ts
  src/web/helpers/i18n.spec.ts
Labels: size/L

#172 1. add tests 2. increase coverage threshold
  .github/workflows/basic-check.yml
  jest.config.js
  package.json
  src/web/helpers/bezier-fit-curve.spec.ts
  src/web/helpers/bezier-fit-curve.ts
  src/web/helpers/check-questionnaire.spec.ts
  src/web/helpers/check-questionnaire.ts
  src/web/helpers/device-list.spec.ts
  src/web/helpers/device-list.ts
  src/web/helpers/menubar/view.spec.ts
  src/web/setupTests.ts
  yarn.lock
Labels: size/XL

#179 remove recent due to the security reason that js is not able to read the full path of local file system
  src/web/app/lang/de.ts
  src/web/app/lang/en.ts
  src/web/app/lang/es.ts
  src/web/app/lang/ja.ts
  src/web/app/lang/zh-cn.ts
  src/web/app/lang/zh-tw.ts
  src/web/app/views/beambox/TopBar/Menu.tsx
  src/web/interfaces/ILang.d.ts
Labels: size/XS

#180 turn it to camel case
  src/web/app/views/beambox/DxfDpiSelector.tsx
  src/web/app/views/beambox/__snapshots__/DxfDpiSelector.spec.tsx.snap
Labels: size/S

#181 add tests
  src/web/app/views/beambox/Right-Panels/Object-Panel.tsx
  src/web/app/views/beambox/Right-Panels/Options-Panel.tsx
  src/web/app/views/beambox/Right-Panels/OptionsPanel.spec.tsx
  src/web/app/views/beambox/Right-Panels/OptionsPanel.tsx
  src/web/app/views/beambox/Right-Panels/PathEditPanel.spec.tsx
  src/web/app/views/beambox/Right-Panels/PathEditPanel.tsx
  src/web/app/views/beambox/Right-Panels/Right-Panel.tsx
  src/web/app/views/beambox/Right-Panels/__snapshots__/OptionsPanel.spec.tsx.snap
  src/web/app/views/beambox/Right-Panels/__snapshots__/PathEditPanel.spec.tsx.snap
  src/web/app/views/beambox/TopBar/FileName.spec.tsx
  src/web/app/views/beambox/TopBar/FileName.tsx
  src/web/app/views/beambox/TopBar/TopBar.tsx
  src/web/app/views/beambox/TopBar/__snapshots__/FileName.spec.tsx.snap
Labels: size/XL

#182 fix the bug that array action popup does not appear in web version
  src/web/app/views/beambox/ToolPanels/ToolPanels.tsx
Labels: size/XS

#183 Update bb2 hw size
  src/web/app/actions/beambox/constant.ts
  src/web/app/constants/device-constants.ts
  src/web/app/views/beambox/DocumentPanel/DocumentPanel.tsx
  src/web/app/views/settings/Editor.tsx
Labels: size/M

#184 remove unnecessary condition check
  src/web/helpers/websocket.ts
Labels: size/XS

#185 create a class name for menu icon
  src/web/app/views/beambox/TopBar/Menu.tsx
  src/web/app/views/beambox/TopBar/__snapshots__/Menu.spec.tsx.snap
Labels: size/M

#186 Fix dxf2svg float calculation
  public/js/lib/dxf2svg.js
Labels: size/S
