Repository flux3dp/beam-studio-core, pull requests merged in 2021-05, with the labels that each got.

#4 fix all tests
  .eslintignore
  .eslintrc.json
  .github/workflows/beam-studio-core-ci.yml
  jest.config.integration.only.js
  jest.config.js
  jest.config.spec.only.js
  package.json
  src/web/app/pages/Connect-Ethernet.tsx
  src/web/app/pages/Connect-Wi-Fi.tsx
  src/web/app/pages/Connect-Wired.tsx
  src/web/app/pages/Select-Connection-Type.tsx
  src/web/app/pages/Select-Machine-Type.tsx
  src/web/app/pages/Settings.tsx
  src/web/app/pages/Skip-Connect-Machine.tsx
  src/web/app/pages/__snapshots__/Connect-Ethernet.spec.tsx.snap
  src/web/app/pages/__snapshots__/Connect-Wi-Fi.spec.tsx.snap
  src/web/app/pages/__snapshots__/Connect-Wired.spec.tsx.snap
  src/web/app/pages/__snapshots__/Select-Connection-Type.spec.tsx.snap
  src/web/app/pages/__snapshots__/Select-Machine-Type.spec.tsx.snap
  src/web/app/pages/__snapshots__/Skip-Connect-Machine.spec.tsx.snap
  src/web/app/pages/__snapshots__/svg-editor.spec.tsx.snap
  src/web/app/pages/svg-editor.spec.tsx
  src/web/app/pages/svg-editor.tsx
  src/web/app/views/beambox/Image-Trace-Panel.tsx
  src/web/app/views/beambox/Right-Panels/Right-Panel.tsx
  src/web/app/views/beambox/Right-Panels/contexts/RightPanelContext.tsx
  src/web/app/views/beambox/Task-Interpreter-Panel.tsx
  src/web/app/views/settings/Setting-General.tsx
  src/web/app/widgets/Dialog-Box.spec.tsx
  src/web/app/widgets/Dialog-Box.tsx
  src/web/app/widgets/Draggble-Window.tsx
  src/web/app/widgets/Modal-With-Hole.spec.tsx
  src/web/app/widgets/Modal-With-Hole.tsx
  src/web/app/widgets/Modal.tsx
  src/web/app/widgets/Slider-Control.tsx
  src/web/app/widgets/Switch-Control.tsx
  src/web/app/widgets/Unit-Input-v2.tsx
  src/web/app/widgets/__snapshots__/Dialog-Box.spec.tsx.snap
  src/web/app/widgets/__snapshots__/Modal-With-Hole.spec.tsx.snap
  src/web/app/widgets/__snapshots__/Switch-Control.spec.tsx.snap
  src/web/helpers/api/image-tracer.ts
  src/web/helpers/pad-string.ts
  src/web/helpers/storage-helper.ts
  src/web/setupTests.ts
  yarn.lock
Labels: size/XXL

#6 make gulp happy
  .github/workflows/beam-studio-core-ci.yml
  .gitignore
  src/web/app/actions/beambox/Image-Trace-Panel-Controller.tsx
  src/web/app/actions/beambox/Tool-Panels-Controller.tsx
  src/web/app/actions/dialog-caller.tsx
  src/web/app/actions/monitor-controller.tsx
  src/web/app/constants/device-constants.ts
  src/web/app/constants/keycode-constants.ts
  src/web/app/constants/macOS-Window-Size.ts
  src/web/app/constants/monitor-constants.ts
  src/web/app/constants/noun-project-constants.ts
  src/web/app/contexts/Dialog-Context.tsx
  src/web/app/contexts/Monitor-Context.tsx
  src/web/app/pages/Beambox.tsx
  src/web/app/views/beambox/About-Beam-Studio.tsx
  src/web/app/views/beambox/Document-Panels/Document-Panel.tsx
  src/web/app/views/beambox/Image-Trace-Panel.tsx
  src/web/app/views/beambox/Layer-Color-Config.tsx
  src/web/app/views/beambox/Network-Testing-Panel.tsx
  src/web/app/views/beambox/Noun-Project-Panel.tsx
  src/web/app/views/beambox/Photo-Edit-Panel.tsx
  src/web/app/views/beambox/Svg-Nest-Buttons.tsx
  src/web/app/views/beambox/Task-Interpreter-Panel.tsx
  src/web/app/views/beambox/Time-Estimation-Button/Time-Estimation-Button.tsx
  src/web/app/views/beambox/Tool-Panels/Tool-Panels.tsx
  src/web/app/views/beambox/Top-Bar/Top-Bar.tsx
  src/web/app/views/beambox/Zoom-Block/Zoom-Block.tsx
  src/web/app/views/dialogs/Change-Log.tsx
  src/web/app/views/dialogs/Confirm-Prompt.tsx
  src/web/app/views/dialogs/DeviceSelector.tsx
  src/web/app/views/dialogs/Prompt.tsx
  src/web/app/views/monitor/Monitor.tsx
  src/web/app/views/tutorials/Tutorial.tsx
  src/web/app/widgets/Dialog-Box.tsx
  src/web/app/widgets/Input-Lightbox.tsx
  src/web/app/widgets/PathInput.tsx
  src/web/app/widgets/Progress.tsx
  src/web/app/widgets/Raw-Move-Panel.tsx
  src/web/app/widgets/Select.spec.tsx
  src/web/app/widgets/Select.tsx
  src/web/app/widgets/Showable-Password-Input.tsx
  src/web/app/widgets/Validation-Text-Input.spec.tsx
  src/web/app/widgets/Validation-Text-Input.tsx
  src/web/app/widgets/__snapshots__/Select.spec.tsx.snap
  src/web/app/widgets/__snapshots__/Validation-Text-Input.spec.tsx.snap
  src/web/interfaces/IDialog.d.ts
  src/web/interfaces/ITutorial.d.ts
Labels: size/XXL

#10 Add use last config button in Camera Calibration
  .eslintrc.json
  src/web/app/actions/beambox/preview-mode-controller.ts
  src/web/app/lang/de.ts
  src/web/app/lang/en.ts
  src/web/app/lang/es.ts
  src/web/app/lang/ja.ts
  src/web/app/lang/zh-cn.ts
  src/web/app/lang/zh-tw.ts
  src/web/app/views/beambox/Camera-Calibration.tsx
  src/web/interfaces/ILang.d.ts
Labels: enhancement, size/XXL

#13 keep interface here and move out implementations to children repos
  .eslintrc.json
  jest.config.js
  src/implementations/storage.ts
  src/tsconfig.json
  src/web/app/pages/Skip-Connect-Machine.tsx
  src/web/app/pages/__snapshots__/Skip-Connect-Machine.spec.tsx.snap
  src/web/helpers/storage-helper.spec.ts
  src/web/helpers/storage-helper.ts
  src/web/interfaces/IStorage.d.ts
Labels: size/L

#12 Add more sentry event
  src/web/app/actions/beambox/beambox-init.ts
  src/web/app/pages/Beambox.tsx
  src/web/app/svgedit/svgcanvas.ts
  src/web/helpers/api/discover.ts
  src/web/helpers/sentry-helper.ts
Labels: size/XXL

#14 Fix exported svg file size
  public/js/lib/svgeditor/recalculate.js
  src/web/app/actions/beambox/export-funcs.ts
  src/web/app/actions/global.ts
  src/web/app/svgedit/svgcanvas.ts
  src/web/helpers/file-export-helper.ts
  src/web/helpers/units.ts
Labels: bug, size/XXL

#11 Fix guiles origin broken layout
  src/web/app/views/settings/Setting-General.tsx
Labels: size/XS

#16 Add a dumb file when initing auto-save-helper
  src/web/helpers/auto-save-helper.ts
Labels: size/M

#19 Improve pathAction.fixEnd speed
  src/web/app/contexts/Monitor-Context.tsx
  src/web/app/lang/de.ts
  src/web/app/lang/en.ts
  src/web/app/lang/es.ts
  src/web/app/lang/ja.ts
  src/web/app/lang/zh-cn.ts
  src/web/app/lang/zh-tw.ts
  src/web/app/svgedit/svgcanvas.ts
  src/web/app/views/dialogs/Prompt.tsx
  src/web/helpers/device-master.ts
  src/web/interfaces/ILang.d.ts
Labels: bug, size/XXL

#20 Remove TextbyFluxsvg option from general settings
  src/web/app/actions/beambox/font-funcs.ts
  src/web/app/views/beambox/Right-Panels/Actions-Panel.tsx
  src/web/app/views/settings/Setting-General.tsx
  src/web/interfaces/IFont.d.ts
Labels: enhancement, size/XXL

#21 Fix 1.6.2 alpha verification bugs
  src/web/app/actions/beambox/font-funcs.ts
  src/web/app/actions/beambox/svg-editor.ts
  src/web/app/svgedit/svgcanvas.ts
  src/web/app/views/beambox/Right-Panels/Actions-Panel.tsx
  src/web/helpers/api/svg-laser-parser.ts
  src/web/helpers/pdf-helper.ts
  src/web/helpers/symbol-maker.ts
Labels: bug, size/XXL

#22 Fix v1.5.2 verification bugs
  public/js/lib/svgeditor/recalculate.js
  src/web/helpers/electron-updater.ts
  src/web/main.ts
Labels: bug, size/L

#23 Add nav back button when aborted or completed
  src/web/app/contexts/Monitor-Context.tsx
  src/web/app/views/monitor/Monitor-Header.tsx
  src/web/app/views/monitor/Monitor.tsx
Labels: enhancement, size/M

#24 use import classnames instead of requireNode
  src/web/app/pages/Beambox.tsx
  src/web/app/pages/Connect-Machine-Ip.tsx
  src/web/app/views/beambox/Camera-Calibration.tsx
  src/web/app/views/beambox/Color-Picker-Panel.tsx
  src/web/app/views/beambox/Diode-Calibration.tsx
  src/web/app/views/beambox/Left-Panels/Left-Panel.tsx
  src/web/app/views/beambox/Noun-Project-Panel.tsx
  src/web/app/views/beambox/Photo-Edit-Panel.tsx
  src/web/app/views/beambox/Right-Panels/Actions-Panel.tsx
  src/web/app/views/beambox/Right-Panels/Laser-Manage-Modal.tsx
  src/web/app/views/beambox/Right-Panels/Laser-Panel.tsx
  src/web/app/views/beambox/Right-Panels/Layer-Panel.tsx
  src/web/app/views/beambox/Right-Panels/Object-Panel.tsx
  src/web/app/views/beambox/Right-Panels/Options-Blocks/Infill-Block.tsx
  src/web/app/views/beambox/Right-Panels/Options-Blocks/Text-Options.tsx
  src/web/app/views/beambox/Time-Estimation-Button/Time-Estimation-Button.tsx
  src/web/app/widgets/Alert.tsx
  src/web/app/widgets/Input-Lightbox.tsx
  src/web/app/widgets/Segmented-Control.tsx
Labels: size/L

#25 Add duplicate button to context menu
  src/web/app/actions/beambox/svg-editor.ts
  src/web/app/lang/de.ts
  src/web/app/lang/en.ts
  src/web/app/lang/es.ts
  src/web/app/lang/ja.ts
  src/web/app/lang/zh-cn.ts
  src/web/app/lang/zh-tw.ts
  src/web/app/pages/__snapshots__/svg-editor.spec.tsx.snap
  src/web/app/pages/svg-editor.tsx
  src/web/interfaces/ILang.d.ts
Labels: size/S

#28 Update Alert-And-Progress children key
  src/web/app/contexts/Alert-Progress-Context.tsx
  src/web/app/views/dialogs/Alerts-And-Progress.tsx
  src/web/helpers/api/svg-laser-parser.ts
  src/web/interfaces/IAlert.d.ts
Labels: bug, size/L

#27 Add delete selected elements method to global interation
  src/web/app/actions/beambox/beambox-global-interaction.ts
  src/web/app/actions/beambox/svg-editor.ts
Labels: size/XS

#31 Add anti-aliasing setting
  src/web/app/actions/beambox/beambox-global-interaction.ts
  src/web/app/actions/beambox/beambox-init.ts
  src/web/app/actions/beambox/svg-editor.ts
  src/web/app/lang/de.ts
  src/web/app/lang/en.ts
  src/web/app/lang/es.ts
  src/web/app/lang/ja.ts
  src/web/app/lang/zh-cn.ts
  src/web/app/lang/zh-tw.ts
  src/web/app/svgedit/svgcanvas.ts
  src/web/app/views/settings/Setting-General.tsx
  src/web/helpers/menubar/electron-menubar-helper.ts
  src/web/helpers/menubar/view.ts
  src/web/helpers/pdf-helper.ts
  src/web/interfaces/ILang.d.ts
Labels: enhancement, size/L

#30 remove config, use storage directly instead
  src/web/app/actions/beambox/beambox-init.ts
  src/web/app/actions/beambox/beambox-preference.spec.ts
  src/web/app/actions/beambox/beambox-preference.ts
  src/web/app/actions/beambox/font-funcs.ts
  src/web/app/actions/beambox/svg-editor.ts
  src/web/app/actions/default-machine.ts
  src/web/app/actions/global.ts
  src/web/app/actions/initialize-machine.ts
  src/web/app/pages/Skip-Connect-Machine.spec.tsx
  src/web/app/pages/Skip-Connect-Machine.tsx
  src/web/app/pages/svg-editor.tsx
  src/web/app/svgedit/svgcanvas.ts
  src/web/app/views/Notification-Collection.tsx
  src/web/app/views/Update-Dialog.tsx
  src/web/app/views/beambox/Camera-Calibration.tsx
  src/web/app/views/beambox/Right-Panels/Dimension-Panel.tsx
  src/web/app/views/beambox/Tool-Panels/NestSpacing.tsx
  src/web/app/views/beambox/Top-Bar/Top-Bar.tsx
  src/web/app/views/settings/Setting-General.tsx
  src/web/app/widgets/Unit-Input-v2.tsx
  src/web/helpers/api/alert-config.ts
  src/web/helpers/api/config.spec.ts
  src/web/helpers/api/config.ts
  src/web/helpers/device-master.ts
  src/web/helpers/electron-updater.ts
  src/web/helpers/smart-upnp.ts
  src/web/interfaces/IStorage.d.ts
Labels: size/L

#33 replace self-version sprintf with open source
  package.json
  src/web/app/actions/beambox/beambox-init.ts
  src/web/app/actions/beambox/font-funcs.ts
  src/web/app/actions/beambox/preview-mode-controller.ts
  src/web/app/views/Update-Dialog.spec.tsx
  src/web/app/views/Update-Dialog.tsx
  src/web/app/views/__snapshots__/Update-Dialog.spec.tsx.snap
  src/web/app/views/beambox/Right-Panels/Laser-Panel.tsx
  src/web/app/views/beambox/Top-Bar/Top-Bar.tsx
  src/web/helpers/device-master.ts
  src/web/helpers/electron-updater.ts
  src/web/helpers/sprintf.ts
  yarn.lock
Labels: size/L

#32 Fix document panel workarea bug
  src/web/app/actions/beambox/beambox-init.ts
  src/web/app/actions/beambox/diode-boundary-drawer.ts
  src/web/app/actions/beambox/open-bottom-boundary-drawer.ts
  src/web/app/actions/beambox/preview-mode-background-drawer.ts
  src/web/app/actions/beambox/preview-mode-controller.ts
  src/web/app/actions/beambox/svg-editor.ts
  src/web/app/svgedit/svgcanvas.ts
  src/web/app/views/beambox/Document-Panels/Document-Panel.tsx
  src/web/app/views/beambox/Svg-Nest-Buttons.tsx
  src/web/app/views/beambox/Tool-Panels/Interval.tsx
  src/web/app/views/beambox/Top-Bar/Top-Bar.tsx
  src/web/app/views/settings/Setting-General.tsx
  src/web/app/widgets/Unit-Input-v2.tsx
Labels: size/L

#34 Improve disassemble & rendering performance
  public/js/lib/svgeditor/coords.js
  public/js/lib/svgeditor/math.js
  src/web/app/svgedit/svgcanvas.ts
  src/web/helpers/menubar/electron-menubar-helper.ts
  src/web/helpers/menubar/view.ts
Labels: bug, enhancement, size/M

#35 simplify UpdateDialog
  src/web/app/actions/alert-actions.ts
  src/web/app/actions/beambox/beambox-init.ts
  src/web/app/views/Notification-Collection.tsx
  src/web/app/views/Update-Dialog.spec.tsx
  src/web/app/views/Update-Dialog.tsx
  src/web/app/views/__snapshots__/Update-Dialog.spec.tsx.snap
  src/web/app/views/settings/Setting-General.tsx
  src/web/helpers/firmware-updater.ts
  src/web/interfaces/IStorage.d.ts
Labels: size/L

#36 extract browser behavior
  src/implementations/browser.ts
  src/web/app/actions/alert-caller.tsx
  src/web/app/actions/beambox/beambox-global-interaction.ts
  src/web/app/actions/beambox/beambox-init.ts
  src/web/app/constants/tutorial-constants.tsx
  src/web/app/pages/Connect-Ethernet.spec.tsx
  src/web/app/pages/Connect-Ethernet.tsx
  src/web/app/pages/__snapshots__/Connect-Ethernet.spec.tsx.snap
  src/web/app/views/FluxIdLogin.tsx
  src/web/app/views/beambox/Network-Testing-Panel.tsx
  src/web/app/views/dialogs/Change-Log.tsx
  src/web/app/widgets/Alert.tsx
  src/web/helpers/api/flux-id.ts
  src/web/helpers/browser-helper.ts
  src/web/interfaces/IBrowser.d.ts
Labels: size/XL

#37 Add translation excepts rating
  src/web/app/lang/de.ts
  src/web/app/lang/en.ts
  src/web/app/lang/es.ts
  src/web/app/lang/ja.ts
Labels: enhancement, size/S

#38 Add Rating panel and support rating
  src/web/app/actions/beambox/beambox-init.ts
  src/web/app/actions/dialog-caller.tsx
  src/web/app/lang/de.ts
  src/web/app/lang/en.ts
  src/web/app/lang/es.ts
  src/web/app/lang/ja.ts
  src/web/app/lang/zh-cn.ts
  src/web/app/lang/zh-tw.ts
  src/web/app/views/beambox/Rating-Panel.tsx
  src/web/helpers/api/flux-id.ts
  src/web/helpers/rating-helper.ts
  src/web/interfaces/ILang.d.ts
  src/web/interfaces/IStorage.d.ts
Labels: size/XL

#39 Add info icon and help center urls on Setting-General
  src/web/app/lang/de.ts
  src/web/app/lang/en.ts
  src/web/app/lang/es.ts
  src/web/app/lang/ja.ts
  src/web/app/lang/zh-cn.ts
  src/web/app/lang/zh-tw.ts
  src/web/app/views/settings/Setting-General.tsx
  src/web/interfaces/ILang.d.ts
  src/web/interfaces/IStorage.d.ts
Labels: size/L

#40 import from implementations directly
  jest.config.js
  src/web/app/actions/alert-caller.tsx
  src/web/app/actions/beambox/beambox-global-interaction.ts
  src/web/app/actions/beambox/beambox-init.ts
  src/web/app/actions/beambox/beambox-preference.spec.ts
  src/web/app/actions/beambox/beambox-preference.ts
  src/web/app/actions/beambox/font-funcs.ts
  src/web/app/actions/beambox/svg-editor.ts
  src/web/app/actions/default-machine.ts
  src/web/app/actions/global.ts
  src/web/app/actions/initialize-machine.ts
  src/web/app/constants/tutorial-constants.tsx
  src/web/app/pages/Connect-Ethernet.spec.tsx
  src/web/app/pages/Connect-Ethernet.tsx
  src/web/app/pages/Connect-Machine-Ip.tsx
  src/web/app/pages/Select-Connection-Type.spec.tsx
  src/web/app/pages/Select-Connection-Type.tsx
  src/web/app/pages/Skip-Connect-Machine.spec.tsx
  src/web/app/pages/Skip-Connect-Machine.tsx
  src/web/app/pages/svg-editor.spec.tsx
  src/web/app/pages/svg-editor.tsx
  src/web/app/svgedit/svgcanvas.ts
  src/web/app/views/FluxIdLogin.tsx
  src/web/app/views/Notification-Collection.tsx
  src/web/app/views/Update-Dialog.spec.tsx
  src/web/app/views/Update-Dialog.tsx
  src/web/app/views/beambox/Camera-Calibration.tsx
  src/web/app/views/beambox/Layer-Color-Config.tsx
  src/web/app/views/beambox/Network-Testing-Panel.tsx
  src/web/app/views/beambox/Noun-Project-Panel.tsx
  src/web/app/views/beambox/Right-Panels/Dimension-Panel.tsx
  src/web/app/views/beambox/Right-Panels/Laser-Manage-Modal.tsx
  src/web/app/views/beambox/Right-Panels/Laser-Panel.tsx
  src/web/app/views/beambox/Right-Panels/Options-Blocks/RectOptions.tsx
  src/web/app/views/beambox/Tool-Panels/Interval.tsx
  src/web/app/views/beambox/Tool-Panels/NestSpacing.tsx
  src/web/app/views/beambox/Tool-Panels/OffsetDist.tsx
  src/web/app/views/beambox/Tool-Panels/Tool-Panels.tsx
  src/web/app/views/beambox/Top-Bar/Top-Bar.tsx
  src/web/app/views/dialogs/Change-Log.tsx
  src/web/app/views/settings/Setting-General.tsx
  src/web/app/widgets/Alert.tsx
  src/web/app/widgets/Unit-Input-v2.tsx
  src/web/helpers/api/alert-config.ts
  src/web/helpers/api/discover.ts
  src/web/helpers/api/flux-id.ts
  src/web/helpers/api/svg-laser-parser.ts
  src/web/helpers/auto-save-helper.ts
  src/web/helpers/browser-helper.ts
  src/web/helpers/device-list.ts
  src/web/helpers/device-master.ts
  src/web/helpers/electron-updater.ts
  src/web/helpers/i18n.ts
  src/web/helpers/rating-helper.ts
  src/web/helpers/rsa-key.ts
  src/web/helpers/sentry-helper.ts
  src/web/helpers/smart-upnp.ts
  src/web/helpers/storage-helper.ts
  src/web/helpers/websocket.ts
Labels: size/L

#41 Update Change logs
  src/web/app/views/dialogs/Change-Log.tsx
Labels: size/M

#42 simplify electron dialog
  src/web/app/actions/electron-dialogs.ts
  src/web/app/views/beambox/Right-Panels/Actions-Panel.tsx
  src/web/app/views/beambox/Right-Panels/Laser-Panel.tsx
  src/web/app/widgets/PathInput.tsx
  src/web/helpers/beam-file-helper.ts
  src/web/helpers/file-export-helper.ts
Labels: size/M

#43 Improve handleHistoryEvent time performance
  src/web/app/svgedit/svgcanvas.ts
Labels: enhancement, size/L

#44 Update sharpen panel default value
  src/web/app/views/beambox/Photo-Edit-Panel.tsx
Labels: enhancement, size/XS

#45 Fix and abbreviate help center urls
  src/web/app/lang/de.ts
  src/web/app/lang/en.ts
  src/web/app/lang/es.ts
  src/web/app/lang/ja.ts
  src/web/app/lang/zh-cn.ts
Labels: size/L

#47 Update #845 message
  src/web/app/lang/de.ts
  src/web/app/lang/en.ts
  src/web/app/lang/es.ts
  src/web/app/lang/ja.ts
  src/web/app/lang/zh-cn.ts
  src/web/app/lang/zh-tw.ts
Labels: size/S

#46 Update change log, allow breakline
  src/web/app/views/dialogs/Change-Log.tsx
Labels: enhancement, size/S

#48 Show rating panel only when online
  src/web/helpers/rating-helper.ts
Labels: size/XS

#49 Fix image cropping related bugs
  src/web/app/views/beambox/Photo-Edit-Panel.tsx
  src/web/helpers/image-data.ts
Labels: bug, size/L

#50 Refine photo-edit-panel syntax
  src/web/app/views/beambox/Photo-Edit-Panel.tsx
Labels: size/XS

#52 isNode is always false
  public/js/lib/clipper_unminified.js
  public/js/lib/svg-nest/util/eval.js
  public/js/lib/svg-nest/util/parallel.js
Labels: size/L

#51 Blur active element when alert popup
  src/web/app/views/beambox/Right-Panels/Laser-Manage-Modal.tsx
  src/web/app/views/dialogs/Alerts-And-Progress.tsx
  src/web/app/widgets/Alert.tsx
  src/web/interfaces/ILaserConfig.d.ts
Labels: size/XXL

#53 Refactor history
  public/js/lib/svgeditor/history.js
  public/js/lib/svgeditor/historyrecording.js
  src/web/app/actions/beambox/font-funcs.ts
  src/web/app/actions/beambox/svg-editor.ts
  src/web/app/svgedit/history.ts
  src/web/app/svgedit/historyrecording.ts
  src/web/app/svgedit/svgcanvas.ts
  src/web/app/views/beambox/Image-Trace-Panel.tsx
  src/web/app/views/beambox/Photo-Edit-Panel.tsx
  src/web/app/views/beambox/Right-Panels/Dimension-Panel.tsx
  src/web/app/views/beambox/Right-Panels/Options-Blocks/Image-Options.tsx
  src/web/app/views/beambox/Right-Panels/Options-Blocks/Text-Options.tsx
  src/web/app/views/beambox/Svg-Nest-Buttons.tsx
  src/web/helpers/image-edit.ts
  src/web/helpers/layer-helper.ts
  src/web/helpers/symbol-maker.ts
  src/web/interfaces/IHistory.d.ts
Labels: size/XXL

#55 Add sentry interface
  package.json
  src/implementations/sentry.ts
  src/web/helpers/sentry-helper.ts
Labels: size/S

#56 remove a bit unused parts
  src/web/app/actions/alert-caller.tsx
  src/web/app/actions/beambox/Tool-Panels-Controller.tsx
  src/web/app/actions/beambox/beambox-init.ts
  src/web/app/actions/beambox/open-bottom-boundary-drawer.ts
  src/web/app/actions/beambox/svg-editor.ts
  src/web/app/constants/alert-constants.ts
  src/web/app/views/beambox/Tool-Panels/Tool-Panels.tsx
  src/web/app/views/tutorials/Tutorial-Controller.tsx
Labels: size/L

#57 extract an fs interface
  src/implementations/fileSystem.ts
  src/web/app/actions/beambox/beambox-init.ts
  src/web/app/contexts/Monitor-Context.tsx
  src/web/app/svgedit/svgcanvas.ts
  src/web/app/views/beambox/Right-Panels/Laser-Panel.tsx
  src/web/app/widgets/PathInput.tsx
  src/web/helpers/api/svg-laser-parser.ts
  src/web/helpers/auto-save-helper.ts
  src/web/helpers/beam-file-helper.ts
  src/web/helpers/file-export-helper.ts
  src/web/helpers/output-error.ts
  src/web/helpers/pdf-helper.ts
  src/web/interfaces/IFileSystem.d.ts
Labels: size/L

#58 extract dialog interface
  src/implementations/dialog.ts
  src/web/app/actions/beambox/beambox-init.ts
  src/web/app/actions/electron-dialogs.ts
  src/web/app/contexts/Monitor-Context.tsx
  src/web/app/views/beambox/Right-Panels/Actions-Panel.tsx
  src/web/app/views/beambox/Right-Panels/Laser-Panel.tsx
  src/web/app/widgets/PathInput.tsx
  src/web/helpers/file-export-helper.ts
  src/web/helpers/output-error.ts
  src/web/interfaces/IDialog.d.ts
  src/web/interfaces/IElectron.d.ts
Labels: size/L

#59 Extract fs
  src/web/helpers/output-error.ts
  src/web/interfaces/IFileSystem.d.ts
Labels: size/L, size/XS

#60 remove flux
  src/web/app/actions/alert-actions.ts
  src/web/app/actions/beambox.ts
  src/web/app/actions/beambox/beambox-global-interaction.ts
  src/web/app/actions/beambox/beambox-init.ts
  src/web/app/actions/beambox/preview-mode-background-drawer.ts
  src/web/app/actions/beambox/preview-mode-controller.ts
  src/web/app/actions/global-actions.ts
  src/web/app/constants/beambox-constants.ts
  src/web/app/constants/global-constants.ts
  src/web/app/dispatcher/alert-dispatcher.ts
  src/web/app/dispatcher/beambox-dispatcher.ts
  src/web/app/dispatcher/global-dispatcher.ts
  src/web/app/pages/Beambox.tsx
  src/web/app/stores/alert-store.ts
  src/web/app/stores/beambox-store.ts
  src/web/app/stores/global-store.ts
  src/web/app/svgedit/svgcanvas.ts
  src/web/app/views/Notification-Collection.tsx
  src/web/app/views/beambox/Document-Panels/Document-Panel.tsx
  src/web/app/views/beambox/Image-Trace-Panel.tsx
  src/web/app/views/beambox/Left-Panels/Left-Panel.tsx
  src/web/app/views/beambox/Top-Bar/Top-Bar.tsx
  src/web/helpers/api/inter-process.ts
  src/web/helpers/firmware-updater.ts
  yarn.lock
Labels: size/XXL

#61 1. use import events 2. add axios lib which supports both Node and browser
  package.json
  src/web/app/views/beambox/Noun-Project-Panel.tsx
  src/web/helpers/api/control.ts
  src/web/helpers/api/flux-id.ts
  src/web/helpers/api/open-cv.ts
  yarn.lock
Labels: size/M

#63 Fix ts errors
  src/web/helpers/api/flux-id.ts
  src/web/helpers/api/open-cv.ts
  src/web/helpers/rating-helper.ts
Labels: size/M

#62 remove redux
  src/web/app/action-creators/device.spec.ts
  src/web/app/action-creators/device.ts
  src/web/app/action-creators/monitor.spec.ts
  src/web/app/action-creators/monitor.ts
  src/web/app/constants/action-creator-device.ts
  src/web/app/constants/action-creator-monitor.ts
  src/web/app/reducer/device.ts
  src/web/app/reducer/index.ts
  src/web/app/reducer/monitor.ts
Labels: size/L

#64 Update requireNode('rxjs')
  package.json
  src/web/app/actions/beambox/preview-mode-background-drawer.ts
  src/web/helpers/api/camera.ts
  yarn.lock
Labels: size/L

#65 1. add fontkit 2. extract font-scanner interface
  package.json
  src/implementations/fontScanner.ts
  src/web/app/actions/beambox/beambox-init.ts
  src/web/app/actions/beambox/font-funcs.ts
  src/web/interfaces/IFont.d.ts
  yarn.lock
Labels: size/XL

#66 1. extract an interface for image processor 2. remove unused functions
  src/implementations/imageProcessor.ts
  src/web/app/svgedit/svgcanvas.ts
  src/web/app/views/beambox/Photo-Edit-Panel.tsx
  src/web/app/views/beambox/Right-Panels/Options-Blocks/Image-Options.tsx
  src/web/helpers/jimp-helper.ts
  src/web/interfaces/IImage.d.ts
Labels: size/L

#67 Avoid monitor getReport before last one not ended
  src/web/app/contexts/Monitor-Context.tsx
Labels: bug, size/S
